-- Owner SQL Editor; dedicated accounts only. No durable upgrade or payment.
begin;
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;end$$;
create function pg_temp.denied(query text) returns boolean language plpgsql as $$begin execute query;return false;exception when insufficient_privilege then return true;end$$;
select pg_temp.assert_true('__USER_A__'<>'__USER_B__','two distinct accounts');
delete from public.entitlements where user_id in ('__USER_A__','__USER_B__');
insert into public.subscriptions(user_id,plan,status,expires_at) values ('__USER_A__','free','active',null),('__USER_B__','pro','active',now()+interval '1 day') on conflict(user_id) do update set plan=excluded.plan,status=excluded.status,expires_at=excluded.expires_at;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(pg_temp.denied('select public.get_advanced_insight_data()'),'Free insights denied');
select pg_temp.assert_true(pg_temp.denied('select public.dismiss_insight(''v1:2099-01:TEST:rollback'')'),'Free dismissal denied');
reset role;
update public.subscriptions set plan='plus',expires_at=now()+interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(pg_temp.denied('select public.get_advanced_insight_data()'),'Plus insights denied');
reset role;
update public.subscriptions set plan='pro',expires_at=now()-interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(pg_temp.denied('select public.get_advanced_insight_data()'),'Expired insights denied');
reset role;
update public.subscriptions set expires_at=now()+interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(jsonb_typeof(public.get_advanced_insight_data()->'transactions')='array','Pro insights succeeds');
select public.dismiss_insight('v1:2099-01:TEST:rollback');
select public.dismiss_insight('v1:2099-01:TEST:rollback');
select pg_temp.assert_true((select count(*)=1 from public.insight_dismissals where insight_key='v1:2099-01:TEST:rollback'),'dismissal retry idempotent');
select pg_temp.assert_true(pg_temp.denied('insert into public.insight_dismissals(user_id,insight_key) values(''__USER_B__'',''v1:2099-01:TEST:other'')'),'cannot dismiss for B');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_B__","role":"authenticated"}',true);
select pg_temp.assert_true(not exists(select 1 from public.insight_dismissals where user_id='__USER_A__'),'B cannot read A dismissal');
select pg_temp.assert_true(not (public.get_advanced_insight_data()->'dismissed' ? 'v1:2099-01:TEST:rollback'),'B RPC excludes A dismissal');
reset role;
select 'PASS: advanced analysis assertions; rollback removes fixtures and upgrades' as result;
rollback;
