-- REAL DATABASE TEST, as database owner in SQL Editor, after migration 004.
-- Replace __USER_A__ / __USER_B__ with two disposable Auth user UUIDs.
-- scripts/verify-entitlements.mjs generates .rls-entitlements-test.sql locally.
-- Everything is rolled back. No service_role key, payment or durable activation.
begin;
select set_config('test.user_a','__USER_A__',true),set_config('test.user_b','__USER_B__',true);
create function pg_temp.assert_true(ok boolean, label text) returns void language plpgsql as $$
begin if ok is distinct from true then raise exception 'FAIL: %',label; end if; end $$;
create function pg_temp.denied(command text, expected_code text) returns boolean language plpgsql as $$
begin execute command; return false; exception when others then return sqlstate=expected_code; end $$;
select pg_temp.assert_true(current_setting('test.user_a')<>current_setting('test.user_b'),'two different users');
select pg_temp.assert_true((select count(*)=2 from auth.users where id in (current_setting('test.user_a')::uuid,current_setting('test.user_b')::uuid)),'registered users');
select pg_temp.assert_true(not exists(select 1 from public.profiles where user_id in (current_setting('test.user_a')::uuid,current_setting('test.user_b')::uuid)),'dedicated users without onboarding');
select pg_temp.assert_true(not exists(select 1 from public.subscriptions where user_id in (current_setting('test.user_a')::uuid,current_setting('test.user_b')::uuid) and plan<>'free'),'test accounts must be Free');
select pg_temp.assert_true(not exists(select 1 from public.transactions where user_id in (current_setting('test.user_a')::uuid,current_setting('test.user_b')::uuid)),'test transactions empty');
select pg_temp.assert_true(not exists(select 1 from public.goals where user_id=current_setting('test.user_a')::uuid),'test goals empty');
select pg_temp.assert_true(not exists(select 1 from public.budgets where user_id=current_setting('test.user_a')::uuid),'test budgets empty');
select pg_temp.assert_true(not exists(select 1 from public.categories where user_id=current_setting('test.user_a')::uuid),'test categories empty');
delete from public.subscriptions where user_id=current_setting('test.user_a')::uuid;
select set_config('request.jwt.claim.sub',current_setting('test.user_a'),true);
set local role authenticated;
select pg_temp.assert_true(public.get_entitlement()->>'plan'='free','no subscription => Free');
select pg_temp.assert_true(not (public.get_entitlement()->>'reports_access')::boolean,'no package reports locked');
select pg_temp.assert_true(pg_temp.denied($q$select * from public.get_report_transactions(to_char(now(),'YYYY-MM'))$q$,'42501'),'Free RPC denied');
select pg_temp.assert_true(pg_temp.denied($q$insert into public.subscriptions(user_id,plan,status,expires_at) values(auth.uid(),'pro','active',now()+interval '30 days')$q$,'42501'),'self activation denied');
select pg_temp.assert_true(pg_temp.denied($q$update public.subscriptions set plan='pro',expires_at=now()+interval '30 days' where user_id=current_setting('test.user_b')::uuid$q$,'42501'),'other subscription update denied');
select pg_temp.assert_true(pg_temp.denied($q$delete from public.subscriptions where user_id=auth.uid()$q$,'42501'),'subscription delete denied');
select pg_temp.assert_true(pg_temp.denied($q$update public.plans set reports_access=true where code='free'$q$,'42501'),'plan config cannot be edited');
select pg_temp.assert_true((select count(*)=0 from public.subscriptions where user_id=current_setting('test.user_b')::uuid),'other subscription not readable');
insert into public.transactions(user_id,data) select auth.uid(),jsonb_build_object('amount',20000,'type','income','category','Project','description','quota test','date',to_char(now() at time zone 'Asia/Jakarta','YYYY-MM-DD')) from generate_series(1,50);
select pg_temp.assert_true((select count(*)=50 from public.transactions where user_id=auth.uid()),'exact transaction cap allowed');
select pg_temp.assert_true(pg_temp.denied($q$insert into public.transactions(user_id,data) select auth.uid(),data from public.transactions limit 1$q$,'P0001'),'transaction 51 denied');
update public.transactions set data=jsonb_set(data,'{description}','"edited at cap"') where id=(select id from public.transactions limit 1);
insert into public.categories(user_id,name) select auth.uid(),'test category '||i from generate_series(1,8) i;
select pg_temp.assert_true(pg_temp.denied($q$insert into public.categories(user_id,name) values(auth.uid(),'ninth')$q$,'P0001'),'category 9 denied');
insert into public.goals(user_id,data) values(auth.uid(),' {"name":"one","target":20000,"saved":0,"monthly":0}'::jsonb);
select pg_temp.assert_true(pg_temp.denied($q$insert into public.goals(user_id,data) values(auth.uid(),'{"name":"two","target":20000,"saved":0,"monthly":0}')$q$,'P0001'),'active goal 2 denied');
insert into public.goals(user_id,data) values(auth.uid(),'{"name":"completed","target":20000,"saved":20000,"monthly":0}');
select pg_temp.assert_true(pg_temp.denied($q$update public.goals set data=jsonb_set(data,'{saved}','0') where data->>'name'='completed'$q$,'P0001'),'reopening goal above cap denied');
insert into public.budgets(user_id,data) select auth.uid(),jsonb_build_object('amount',20000,'category',c,'month',to_char(now(),'YYYY-MM'),'mandatory',true) from unnest(array['Makan & minum','Transportasi','Belanja','Tagihan','Kesehatan']) c;
select pg_temp.assert_true(pg_temp.denied($q$insert into public.budgets(user_id,data) values(auth.uid(),jsonb_build_object('amount',20000,'category','Hiburan','month',to_char(now(),'YYYY-MM'),'mandatory',true))$q$,'P0001'),'budget category 6 denied');
reset role;
insert into public.subscriptions(user_id,plan,status,expires_at) values(current_setting('test.user_a')::uuid,'plus','active',now()+interval '30 days');
set local role authenticated;
select pg_temp.assert_true((public.get_entitlement()->>'reports_access')::boolean,'active Plus reports enabled');
insert into public.transactions(user_id,data) select auth.uid(),data from public.transactions limit 1;
insert into public.categories(user_id,name) values(auth.uid(),'premium ninth');
insert into public.goals(user_id,data) values(auth.uid(),'{"name":"premium goal","target":20000,"saved":0,"monthly":0}');
insert into public.budgets(user_id,data) values(auth.uid(),jsonb_build_object('amount',20000,'category','Hiburan','month',to_char(now(),'YYYY-MM'),'mandatory',true));
select pg_temp.assert_true((select count(*)=51 from public.get_report_transactions(to_char(now() at time zone 'Asia/Jakarta','YYYY-MM'))),'active Plus RPC succeeds');
select pg_temp.assert_true(pg_temp.denied($q$update public.subscriptions set plan='free' where user_id=auth.uid()$q$,'42501'),'own subscription update denied');
reset role;
update public.subscriptions set plan='pro',expires_at=now()+interval '30 days' where user_id=current_setting('test.user_a')::uuid;
select set_config('request.jwt.claim.sub',current_setting('test.user_b'),true);
set local role authenticated;
insert into public.transactions(user_id,data) values(auth.uid(),jsonb_build_object('amount',12345,'type','income','category','Project','description','B private','date',to_char(now() at time zone 'Asia/Jakarta','YYYY-MM-DD')));
select pg_temp.assert_true((select count(*)=1 from public.transactions),'B cannot read A finance');
select pg_temp.assert_true((select count(*)=0 from public.budgets),'B cannot read A budgets');
select pg_temp.assert_true((select count(*)=0 from public.goals),'B cannot read A goals');
reset role;
select set_config('request.jwt.claim.sub',current_setting('test.user_a'),true);
set local role authenticated;
select pg_temp.assert_true(public.get_entitlement()->>'plan'='pro','active Pro effective');
select pg_temp.assert_true((select count(*)=51 from public.get_report_transactions(to_char(now() at time zone 'Asia/Jakarta','YYYY-MM'))),'A report excludes B');
select pg_temp.assert_true(not exists(select 1 from public.get_report_transactions(to_char(now() at time zone 'Asia/Jakarta','YYYY-MM')) where data->>'description'='B private'),'report never exposes B');
reset role;
update public.subscriptions set expires_at=now() where user_id=current_setting('test.user_a')::uuid;
set local role authenticated;
select pg_temp.assert_true(public.get_entitlement()->>'plan'='free','expiry exactly now => Free');
reset role;
update public.subscriptions set expires_at=now()-interval '1 second' where user_id=current_setting('test.user_a')::uuid;
set local role authenticated;
select pg_temp.assert_true(public.get_entitlement()->>'plan'='free','expired => Free');
select pg_temp.assert_true(pg_temp.denied($q$select * from public.get_report_transactions(to_char(now(),'YYYY-MM'))$q$,'42501'),'expired reports denied');
select pg_temp.assert_true((select count(*)=51 from public.transactions),'expired data retained');
select pg_temp.assert_true(pg_temp.denied($q$insert into public.transactions(user_id,data) select auth.uid(),data from public.transactions limit 1$q$,'P0001'),'expired above cap insert denied');
update public.transactions set data=jsonb_set(data,'{description}','"editable after expiry"');
insert into public.transactions(id,user_id,data) select id,user_id,jsonb_set(data,'{description}','"upsert after expiry"') from public.transactions limit 1 on conflict(id) do update set data=excluded.data;
select pg_temp.assert_true(pg_temp.denied($q$insert into public.goals(user_id,data) values(auth.uid(),'{"name":"expired new","target":20000,"saved":0,"monthly":0}')$q$,'P0001'),'expired goals above cap denied');
update public.goals set data=jsonb_set(data,'{name}','"editable after expiry"') where data->>'saved'='0';
reset role;
update public.subscriptions set status='cancelled',expires_at=now()+interval '30 days' where user_id=current_setting('test.user_a')::uuid;
set local role authenticated;
select pg_temp.assert_true(public.get_entitlement()->>'plan'='free','cancelled => Free');
reset role;
select 'PASS: all assertions; rollback removes fixtures and temporary upgrades' as result;
rollback;
