begin;
select set_config('test.user_a','__USER_A__',true),set_config('test.user_b','__USER_B__',true);
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;end $$;
create function pg_temp.denied(command text,code text) returns boolean language plpgsql as $$begin execute command;return false;exception when others then return sqlstate=code;end $$;
select pg_temp.assert_true(not exists(select 1 from public.admin_users where user_id in(current_setting('test.user_a')::uuid,current_setting('test.user_b')::uuid)),'disposable non-admin accounts');
insert into public.admin_users(user_id) values(current_setting('test.user_a')::uuid);
insert into storage.objects(bucket_id,name,metadata) values('digital-files',current_setting('test.user_a')||'/test-file.pdf','{"mimetype":"application/pdf","size":100}'),('merchant-qris',current_setting('test.user_a')||'/test-qris.png','{"mimetype":"image/png","size":100}');
select set_config('request.jwt.claim.sub',current_setting('test.user_a'),true);
set local role authenticated;
select set_config('test.product',(public.admin_save_product(jsonb_build_object('code','test-digital','name','TEST FILE ONLY','type','digital_tool','price_rupiah',5000,'duration_days',null,'plan',null,'active',true,'sort_order',0,'description','TEST','promo_starts_at',null,'promo_ends_at',null,'digital_file_path',auth.uid()::text||'/test-file.pdf'))).id::text,true);
select public.admin_save_payment_settings(jsonb_build_object('product_id',current_setting('test.product'),'merchant_name','TEST NO PAYMENT','qris_path',auth.uid()::text||'/test-qris.png','instructions','TEST ONLY','enabled',true,'unique_amount_enabled',false));
select set_config('request.jwt.claim.sub',current_setting('test.user_b'),true);
select set_config('test.order',(public.create_order('test-digital',gen_random_uuid())).id::text,true);
select pg_temp.assert_true(pg_temp.denied($q$select public.get_paid_download(current_setting('test.product')::uuid)$q$,'42501'),'unpaid download denied');
select pg_temp.assert_true(pg_temp.denied($q$select public.admin_save_product('{}')$q$,'42501'),'non-admin product edit denied');
select pg_temp.assert_true(pg_temp.denied($q$select public.admin_save_payment_settings('{}')$q$,'42501'),'non-admin merchant edit denied');
select pg_temp.assert_true(not public.can_read_paid_file(current_setting('test.user_a')||'/test-file.pdf'),'private file inaccessible before paid');
select public.submit_payment_confirmation(current_setting('test.order')::uuid,'TEST-REF');
select set_config('request.jwt.claim.sub',current_setting('test.user_a'),true);
select public.admin_review_order(current_setting('test.order')::uuid,'paid','TEST ONLY');
select pg_temp.assert_true((select count(*)=0 from public.entitlements where source_order_id=current_setting('test.order')::uuid),'file purchase does not grant subscription');
select public.admin_save_product(jsonb_build_object('id',current_setting('test.product'),'code','test-digital','name','TEST NEW NAME','type','digital_tool','price_rupiah',10000,'duration_days',null,'plan',null,'active',false,'sort_order',0,'description','TEST','promo_starts_at',null,'promo_ends_at',null,'digital_file_path',auth.uid()::text||'/test-file.pdf'));
select pg_temp.assert_true((select price_rupiah=5000 and product_name='TEST FILE ONLY' from public.orders where id=current_setting('test.order')::uuid),'catalog edit preserves snapshot');
select set_config('request.jwt.claim.sub',current_setting('test.user_b'),true);
select pg_temp.assert_true(public.get_paid_download(current_setting('test.product')::uuid)=current_setting('test.user_a')||'/test-file.pdf','paid download permitted even after product disabled');
select pg_temp.assert_true(public.can_read_paid_file(current_setting('test.user_a')||'/test-file.pdf'),'storage paid read check');
select pg_temp.assert_true((select count(*)=1 from public.download_logs where user_id=auth.uid()),'download logged');
reset role;
select pg_temp.assert_true((select not public from storage.buckets where id='digital-files'),'digital bucket private');
select 'PASS: product settings, snapshots and private download rights; rollback removes fixtures' as result;
rollback;
