-- Owner SQL Editor, after 013. No lasting data/plan changes; every user query impersonates explicitly.
begin;
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;end$$;
create function pg_temp.denied(q text) returns boolean language plpgsql as $$begin execute q;return false;exception when insufficient_privilege then return true;end$$;
delete from public.entitlements where user_id in ('__USER_A__','__USER_B__');
insert into public.subscriptions(user_id,plan,status,expires_at) values ('__USER_A__','free','active',null),('__USER_B__','pro','active',now()+interval '1 day') on conflict(user_id) do update set plan=excluded.plan,status=excluded.status,expires_at=excluded.expires_at;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(pg_temp.denied('select public.get_forecast_analytics()'),'Free forecast denied');
reset role;
update public.subscriptions set plan='plus',expires_at=now()+interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(pg_temp.denied('select public.get_forecast_analytics()'),'Plus forecast denied');
reset role;
update public.subscriptions set plan='pro',expires_at=now()-interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(pg_temp.denied('select public.get_forecast_analytics()'),'expired forecast denied');
reset role;
update public.subscriptions set expires_at=now()+interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select set_config('test.forecast_rule',public.save_recurring(null,20000,'income','Project','TEST forecast rollback','monthly',(now() at time zone 'Asia/Jakarta')::date+1,null,true)::text,true);
select pg_temp.assert_true(exists(select 1 from jsonb_array_elements(public.get_forecast_analytics()->'recurring') r where r->>'id'=current_setting('test.forecast_rule')),'Pro receives own recurring rule');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_B__","role":"authenticated"}',true);
select pg_temp.assert_true(not exists(select 1 from jsonb_array_elements(public.get_forecast_analytics()->'recurring') r where r->>'id'=current_setting('test.forecast_rule')),'B forecast excludes A rule');
reset role;
select 'PASS: recurring forecast assertions; rollback removes fixtures and upgrades' as result;
rollback;
