-- SQL Editor as owner. Dedicated A/B only. All fixture/upgrade changes rollback.
begin;
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label; end if; end$$;
create function pg_temp.denied(query text) returns boolean language plpgsql as $$begin execute query;return false;exception when insufficient_privilege then return true;end$$;
select pg_temp.assert_true('__USER_A__'<>'__USER_B__','two distinct users');
select pg_temp.assert_true(not exists(select 1 from public.recurring_rules where user_id='__USER_A__'),'A must have no existing rules');
delete from public.entitlements where user_id in ('__USER_A__','__USER_B__');
insert into public.subscriptions(user_id,plan,status,expires_at) values ('__USER_A__','free','active',null),('__USER_B__','plus','active',now()+interval '1 day') on conflict(user_id) do update set plan=excluded.plan,status=excluded.status,expires_at=excluded.expires_at;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(pg_temp.denied('select public.apply_recurring()'),'Free apply denied');
select pg_temp.assert_true(pg_temp.denied('select public.save_recurring(null,20000,''expense'',''Tagihan'',''TEST'',''monthly'',''2024-01-31'',''2024-03-31'',true)'),'Free save denied');
reset role;
update public.subscriptions set plan='plus',expires_at=now()+interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(public.recurring_next('2024-01-31','monthly','2024-01-31')='2024-02-29','leap February');
select pg_temp.assert_true(public.recurring_next('2024-01-31','monthly','2024-02-29')='2024-03-31','restores day 31');
select set_config('test.rule',public.save_recurring(null,20000,'expense','Tagihan','TEST rollback','monthly','2024-01-31','2024-03-31',true)::text,true);
select public.apply_recurring();
select pg_temp.assert_true((select count(*)=3 from public.recurring_occurrences where rule_id=current_setting('test.rule')::uuid),'three missed dates generated');
select pg_temp.assert_true((public.apply_recurring()->>'created')::int=0,'repeat generates nothing');
-- Generated transactions remain editable; deletion does not reopen the due date.
update public.transactions set data=jsonb_set(data,'{amount}','25000') where id in (select transaction_id from public.recurring_occurrences where rule_id=current_setting('test.rule')::uuid);
delete from public.transactions where id in (select transaction_id from public.recurring_occurrences where rule_id=current_setting('test.rule')::uuid);
select pg_temp.assert_true((public.apply_recurring()->>'created')::int=0,'deleted transactions not replayed');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_B__","role":"authenticated"}',true);
select pg_temp.assert_true(not exists(select 1 from public.recurring_rules where id=current_setting('test.rule')::uuid),'B cannot read A rules');
select pg_temp.assert_true(not exists(select 1 from public.recurring_occurrences where rule_id=current_setting('test.rule')::uuid),'B cannot read A ledger');
select pg_temp.assert_true(pg_temp.denied(format('select public.delete_recurring(%L)',current_setting('test.rule'))),'B cannot delete A rules');
reset role;
update public.subscriptions set expires_at=now()-interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true(pg_temp.denied('select public.apply_recurring()'),'expired apply denied');
select pg_temp.assert_true(not exists(select 1 from public.recurring_rules where id=current_setting('test.rule')::uuid),'expired rules locked');
reset role;
select 'PASS: recurring assertions; rollback removes fixtures and upgrades' as result;
rollback;
