-- Owner SQL Editor only; dedicated users, no real payments, all fixtures rollback.
begin;
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;end$$;
create function pg_temp.denied(q text) returns boolean language plpgsql as $$begin execute q;return false;exception when insufficient_privilege then return true;end$$;
select pg_temp.assert_true('__USER_A__'<>'__USER_B__','distinct accounts');
select pg_temp.assert_true(not exists(select 1 from public.transactions where user_id in('__USER_A__','__USER_B__')),'dedicated empty finance accounts');
delete from public.entitlements where user_id in('__USER_A__','__USER_B__');
delete from public.admin_users where user_id='__USER_A__';
insert into public.admin_users(user_id) values('__USER_B__') on conflict do nothing;
insert into public.subscriptions(user_id,plan,status,expires_at) values('__USER_A__','free','active',null),('__USER_B__','free','active',null) on conflict(user_id) do update set plan=excluded.plan,status=excluded.status,expires_at=excluded.expires_at;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
insert into public.transactions(user_id,data) values('__USER_A__','{"type":"income","amount":20000,"category":"Project","date":"2026-10-03","description":"RELEASE-TEST-A"}');
select pg_temp.assert_true((public.get_entitlement()->>'plan')='free','Free export gate');
select pg_temp.assert_true(pg_temp.denied('select public.admin_list_orders()'),'non-admin RPC denied');
select set_config('request.jwt.claims','{"sub":"__USER_B__","role":"authenticated"}',true);
insert into public.transactions(user_id,data) values('__USER_B__','{"type":"income","amount":20000,"category":"Project","date":"2026-10-03","description":"RELEASE-TEST-B"}');
reset role;
update public.subscriptions set plan='plus',expires_at=now()+interval '1 day' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true((public.get_entitlement()->>'plan')='plus','active Plus export gate');
select pg_temp.assert_true((select count(*)=1 from public.transactions),'export query only owner rows');
select pg_temp.assert_true(not exists(select 1 from public.transactions where user_id='__USER_B__'),'A cannot export B');
reset role;
update public.subscriptions set expires_at=now()-interval '1 second' where user_id='__USER_A__';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_A__","role":"authenticated"}',true);
select pg_temp.assert_true((public.get_entitlement()->>'plan')='free','expired export denied');
reset role;
insert into public.products(code,name,type,price_rupiah,duration_days,plan,active) values('release-test-only','TEST no payment','subscription',9900,30,'plus',false);
insert into public.orders(order_number,user_id,product_id,request_id,product_name,product_type,price_rupiah,total_rupiah,duration_days,plan,merchant_name,qris_path,payment_instructions,status,expires_at)
select 'RELEASE-TEST-'||i,'__USER_A__',p.id,gen_random_uuid(),'TEST no payment','subscription',9900,9900,30,'plus','TEST','no-file','No payment','submitted',now()+interval '1 day' from public.products p cross join generate_series(1,3) i where p.code='release-test-only';
insert into public.payment_confirmations(order_id,user_id,reference) select id,user_id,case order_number when 'RELEASE-TEST-1' then ' Reference-DUP ' when 'RELEASE-TEST-2' then 'reference-dup' else 'reference-unique' end from public.orders where order_number like 'RELEASE-TEST-%';
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"__USER_B__","role":"authenticated"}',true);
select pg_temp.assert_true((select count(*)=2 from jsonb_array_elements(public.admin_list_orders(p_search=>'RELEASE-TEST-')) x where (x->>'duplicate_reference')::boolean),'case/whitespace duplicates flagged');
select pg_temp.assert_true((select count(*)=1 from jsonb_array_elements(public.admin_list_orders(p_search=>'RELEASE-TEST-')) x where not (x->>'duplicate_reference')::boolean),'unique reference not flagged');
select pg_temp.assert_true(not exists(select 1 from public.transactions where user_id='__USER_A__'),'admin cannot read owner finance');
reset role;
select pg_temp.assert_true(not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in('r','p') and not c.relrowsecurity),'all public tables RLS');
select pg_temp.assert_true((select count(*)=2 and bool_and(not public) from storage.buckets where id in('payment-proofs','digital-files')),'private buckets');
select 'PASS: release Phase 2 assertions; no payment; all fixtures rollback' as result;
rollback;
