begin;
select set_config('test.user_a','__USER_A__',true),set_config('test.user_b','__USER_B__',true);
create function pg_temp.assert_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;end $$;
create function pg_temp.denied(command text,code text) returns boolean language plpgsql as $$begin execute command;return false;exception when others then return sqlstate=code;end $$;
select pg_temp.assert_true(not exists(select 1 from public.admin_users where user_id in(current_setting('test.user_a')::uuid,current_setting('test.user_b')::uuid)),'test accounts not already admins');
insert into public.admin_users(user_id) values(current_setting('test.user_a')::uuid);
select set_config('test.published',coalesce((select content::text from public.site_content_published where id=1),'null'),true),set_config('test.revision',coalesce((select revision::text from public.site_content_draft where id=1),'0'),true);
select set_config('request.jwt.claim.sub',current_setting('test.user_b'),true);
set local role authenticated;
select pg_temp.assert_true((select count(*)=0 from public.site_content_draft),'non-admin draft unreadable');
select pg_temp.assert_true(pg_temp.denied($q$select public.admin_save_site_draft('{}',0)$q$,'42501'),'non-admin save denied');
select pg_temp.assert_true(pg_temp.denied($q$select public.admin_publish_site(1)$q$,'42501'),'non-admin publish denied');
select set_config('request.jwt.claim.sub',current_setting('test.user_a'),true);
select pg_temp.assert_true(pg_temp.denied($q$select public.admin_save_site_draft('{}',0)$q$,'22023'),'missing fields rejected');
select pg_temp.assert_true(not public.valid_site_destination('javascript:alert(1)') and not public.valid_site_destination('//evil.example') and not public.valid_site_destination('/'||chr(92)||'evil') and public.valid_site_destination('/?auth=register'),'CTA validation');
select set_config('test.newrevision',(public.admin_save_site_draft('{"logo_path":null,"headline":"TEST DRAFT ONLY","description":"TEST","cta_label":"TEST","cta_url":"/?auth=register","feature_heading":"TEST","features":[{"title":"TEST","description":"TEST"}],"steps":[{"title":"TEST","description":"TEST"}],"footer":"TEST"}',current_setting('test.revision')::integer)).revision::text,true);
select pg_temp.assert_true(coalesce((select content::text from public.site_content_published where id=1),'null')=current_setting('test.published'),'draft does not change published');
select pg_temp.assert_true(pg_temp.denied($q$select public.admin_publish_site(999999)$q$,'22023'),'stale publish denied');
select public.admin_publish_site(current_setting('test.newrevision')::integer);
select pg_temp.assert_true((select published_by=auth.uid() and published_at is not null and content->>'headline'='TEST DRAFT ONLY' from public.site_content_published where id=1),'published content attributed');
reset role;
set local role anon;
select pg_temp.assert_true((select content->>'headline'='TEST DRAFT ONLY' from public.site_content_published where id=1),'anonymous sees only published');
select pg_temp.assert_true(pg_temp.denied($q$select * from public.site_content_draft$q$,'42501'),'anonymous draft denied');
reset role;
select 'PASS: CMS draft isolation, validation, versioned publish; rollback restores content' as result;
rollback;
