'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ShieldCheck,Receipt,History,TriangleAlert} from 'lucide-react';
import {orderApi} from '@/lib/order-api';
import {rupiah} from '@/lib/finance';
import {orderStatus,type Order} from '@/lib/checkout';
import Wordmark from './wordmark';
type Purchase=Order&{buyer_name:string;buyer_email:string;reference:string|null;confirmation_note:string|null;proof_path:string|null;duplicate_reference:boolean;access_ends_at:string|null;reviewed_at:string|null;review_note:string|null;submitted_at:string|null};
type Audit={id:string;admin_id:string;action:string;object_id:string;created_at:string;before_data:unknown;after_data:unknown};
type Summary={users:number;statuses:Record<string,number>;verified_count:number;subscription_revenue:number;tools_revenue:number;active_plans:number};
const date=(s:string|null)=>s?new Date(s).toLocaleString('id-ID'):'—';
export default function AdminPurchases(){
 const [data,setData]=useState<{summary:Summary;orders:Purchase[];audit:Audit[]}|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Purchase|null>(null),[note,setNote]=useState(''),[verified,setVerified]=useState(false),[proof,setProof]=useState(''),[filters,setFilters]=useState({search:'',status:'',product:'',from:'',to:'',offset:0});
 async function load(f=filters){setBusy(true);setError('');try{const params=new URLSearchParams(Object.entries(f).map(([k,v])=>[k,String(v)]));setData(await orderApi(`/api/admin/purchases?${params}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load(); // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 async function review(decision:'paid'|'rejected'){if(!selected)return;setBusy(true);setError('');try{const result=await orderApi('/api/admin/purchases',{order_id:selected.id,decision,note});setMessage(result.result==='already_paid'?'Pesanan sudah disetujui. Akses tidak ditambahkan lagi.':decision==='paid'?'Pembayaran ditandai terverifikasi.':'Pesanan ditolak dengan catatan.');setSelected(null);setProof('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function openProof(){if(!selected)return;try{const r=await orderApi(`/api/admin/proof?order=${selected.id}`);setProof(r.url);setTimeout(()=>setProof(''),60000);}catch(e){setError((e as Error).message);}}
 return <div className="admin-shell"><header className="admin-header"><Wordmark/><nav aria-label="Admin"><Link href="/admin" aria-current="page">Pembelian</Link><Link href="/admin/settings">Produk & QRIS</Link><Link href="/admin/content">Konten</Link></nav><Link href="/">Kembali ke aplikasi</Link><button className="text-button" onClick={async()=>{await fetch('/api/admin/session',{method:'DELETE'});window.location.assign('/admin/connect');}}>Tutup sesi admin</button></header><main><div className="section-heading"><div><span className="eyebrow">ADMIN · PEMBELIAN</span><h1>Verifikasi dengan jelas.</h1><p className="muted">Periksa penerimaan di akun merchant sebelum menyetujui. Konfirmasi pengguna bukan bukti dana diterima.</p></div><ShieldCheck size={28}/></div>
 {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status" className="admin-success">{message}</p>}
 {data&&<section className="admin-summary" aria-label="Ringkasan"><div className="panel admin-revenue"><span>Pendapatan langganan terverifikasi</span><strong className="money">{rupiah(data.summary.subscription_revenue)}</strong><small>Tools: {rupiah(data.summary.tools_revenue)} · hanya pesanan paid</small></div><div className="panel"><span>Pengguna</span><strong>{data.summary.users}</strong><small>{data.summary.active_plans} akun dengan paket aktif</small></div><div className="panel"><span>Menunggu verifikasi</span><strong>{data.summary.statuses.submitted||0}</strong><small>{data.summary.verified_count} pembayaran terverifikasi</small>{Object.entries(data.summary.statuses).map(([status,n])=><small key={status}>{orderStatus[status as keyof typeof orderStatus]}: {n}</small>)}</div></section>}
 <section className="panel"><h2><Receipt size={20}/> Pesanan</h2><form className="admin-filters" onSubmit={e=>{e.preventDefault();const next={...filters,offset:0};setFilters(next);void load(next);}}><label>Cari pembeli / pesanan<input value={filters.search} maxLength={120} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Email atau ID pesanan"/></label><label>Status<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Semua status</option>{Object.entries(orderStatus).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>ID produk (opsional)<input value={filters.product} onChange={e=>setFilters({...filters,product:e.target.value})} placeholder="UUID produk"/></label><label>Dari<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Sampai<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><button className="button secondary" disabled={busy}>Terapkan</button></form>
 {busy&&<div className="skeleton review-skeleton" aria-label="Memuat pembelian" role="status"/>}{data&&!busy&&data.orders.length===0&&<p className="empty">Belum ada pesanan yang sesuai. Coba ubah filter.</p>}
 <div className="admin-order-list">{data?.orders.map(o=><button className="admin-order" key={o.id} onClick={()=>{setSelected(o);setNote('');setVerified(false);setProof('');}}><span><strong>{o.product_name}</strong><small>{o.buyer_name||o.buyer_email} · {o.order_number}</small><small>{date(o.created_at)} · akses sampai {date(o.access_ends_at)}</small></span><span><strong className="money">{rupiah(o.total_rupiah)}</strong><small>{orderStatus[o.status]}</small>{o.duplicate_reference&&<small className="warning">Referensi duplikat</small>}</span></button>)}</div><div className="hero-actions"><button className="button secondary" disabled={busy||filters.offset===0} onClick={()=>{const f={...filters,offset:Math.max(0,filters.offset-50)};setFilters(f);void load(f);}}>Sebelumnya</button><button className="button secondary" disabled={busy||!data||data.orders.length<50} onClick={()=>{const f={...filters,offset:filters.offset+50};setFilters(f);void load(f);}}>Berikutnya</button></div></section>
 {selected&&<section className="panel admin-detail" aria-label="Detail pesanan"><div className="section-heading"><h2>{selected.order_number}</h2><button className="text-button" onClick={()=>{setSelected(null);setProof('');}}>Tutup detail</button></div><p>{selected.buyer_email} · {selected.product_name}</p><dl><dt>Harga snapshot</dt><dd className="money">{rupiah(selected.price_rupiah)} + {rupiah(selected.unique_amount)} = {rupiah(selected.total_rupiah)}</dd><dt>Masa akses snapshot</dt><dd>{selected.duration_days?`${selected.duration_days} hari`:'Unduhan produk'}</dd><dt>Referensi</dt><dd>{selected.reference||'Belum dikirim'}</dd><dt>Catatan pembeli</dt><dd>{selected.confirmation_note||'—'}</dd></dl>{selected.duplicate_reference&&<p className="warning"><TriangleAlert size={18}/> Referensi ini juga digunakan pada pesanan lain. Cocokkan mutasi merchant.</p>}{selected.proof_path&&<button className="button secondary" onClick={openProof}>Buka bukti privat (60 detik)</button>}{proof&&<Image unoptimized src={proof} width={600} height={600} className="admin-proof" alt="Bukti pembayaran privat"/>}
 <ol className="admin-timeline"><li>Dibuat · {date(selected.created_at)}</li>{selected.submitted_at&&<li>Konfirmasi dikirim · {date(selected.submitted_at)}</li>}{selected.reviewed_at&&<li>{orderStatus[selected.status]} · {date(selected.reviewed_at)} · {selected.review_note||'Tanpa catatan'}</li>}</ol>
 {selected.status==='submitted'&&<div className="form"><label>Catatan pemeriksaan (wajib jika ditolak)<textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Saya sudah memeriksa dana benar-benar diterima di akun merchant.</label><div className="hero-actions"><button className="button primary" disabled={busy||!verified} onClick={()=>review('paid')}>Setujui pembayaran</button><button className="button secondary" disabled={busy||!note.trim()} onClick={()=>review('rejected')}>Tolak dengan catatan</button></div></div>}</section>}
 <section className="panel"><h2><History size={20}/> Riwayat tindakan admin</h2><p className="muted">50 tindakan terbaru. Log tidak dapat diedit atau dihapus melalui aplikasi.</p>{data?.audit.length===0&&<p className="empty">Belum ada tindakan admin.</p>}{data?.audit.map(a=><details key={a.id} className="admin-audit"><summary>{a.action} · {date(a.created_at)}</summary><small>Admin {a.admin_id} · objek {a.object_id}</small><pre>{JSON.stringify({sebelum:a.before_data,sesudah:a.after_data},null,2)}</pre></details>)}</section></main></div>;
}
