'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {LockKeyhole} from 'lucide-react';import {supabase} from '@/lib/supabase';import type {advancedInsights} from '@/lib/finance/insights';
type Result=ReturnType<typeof advancedInsights>&{date:string};
export default function AdvancedInsights(){const [result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[locked,setLocked]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 async function call(key?:string){const session=(await supabase?.auth.getSession())?.data.session;if(!session){setLocked(true);setResult(null);return null;}const r=await fetch('/api/advanced-insights',{method:key?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:key?JSON.stringify({key}):undefined,cache:'no-store'});if(r.status===403||r.status===401){setLocked(true);setResult(null);return null;}const body=await r.json();if(!r.ok)throw new Error(body.error);setLocked(false);return body;}
 useEffect(()=>{let alive=true;async function load(){try{const body=await call();if(alive){setResult(body);setError('');}}catch(e){if(alive){setResult(null);setError((e as Error).message);}}finally{if(alive)setLoading(false);}}void load();window.addEventListener('focus',load);const timer=setInterval(load,60000);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',load);};},[]);
 async function dismiss(key:string){setBusy(key);setError('');try{if(await call(key))setResult(await call());}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 if(loading)return <div className="skeleton review-skeleton" role="status" aria-label="Memeriksa insight"/>;
 if(locked)return <section className="panel form"><LockKeyhole/><h1>Insight dari kebiasaanmu</h1><p>Pro membantu mengenali perubahan kategori, transaksi besar, dan kebiasaan yang membaik.</p><Link className="button primary" href="/?view=premium">Upgrade ke Pro</Link></section>;
 return <section className="panel form"><h1>Insight keuangan</h1><p className="muted">Prioritas berdasarkan data aktual, tanpa AI. Maksimal 5 insight sekaligus.</p>{error&&<p className="form-error" role="alert">{error}</p>}{result&&!result.eligible&&<p>Data belum cukup. Catat pengeluaran bulan sebelumnya dan minimal 3 pengeluaran bulan ini.</p>}{result?.eligible&&!result.items.length&&<p>Tidak ada perubahan yang melewati ambang, atau insight sudah kamu abaikan. Terus catat transaksi untuk melihat perubahan berikutnya.</p>}{result?.items.map(i=><article key={i.key}><h2>{i.title}</h2><p>{i.text}</p><details><summary>Asumsi perhitungan</summary><p className="muted">{i.assumption}</p></details><button className="button secondary" disabled={!!busy} onClick={()=>dismiss(i.key)}>{busy===i.key?'Menyimpan…':'Abaikan insight ini'}</button></article>)}<details><summary>Ambang dan urutan prioritas</summary><p>Transaksi besar → kenaikan kategori → kenaikan terhadap 3 bulan → kategori baru → perbaikan → hari dengan pengeluaran terkumpul. Pembanding kategori memakai hari yang sama pada bulan sebelumnya agar bulan berjalan tidak dibandingkan dengan satu bulan penuh. Insight diabaikan disimpan hanya untuk akunmu; kunci berubah tiap bulan.</p></details></section>;
}
