'use client';
import { useEffect, useState } from 'react';
import { LayoutDashboard, ArrowLeftRight, ChartPie, Target, Settings, Plus, ArrowUpRight, ArrowDownLeft, ChevronRight, LogOut, Search, Pencil, Trash2, X, Check, TrendingUp, ShieldCheck, ArrowRight } from 'lucide-react';
import * as Dialog from '@radix-ui/react-dialog';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import Wordmark from './wordmark';
import SupportLink from './support-link';
import Landing from './landing';
import {BudgetRow,GoalRow} from './finance-rows';
import {type SiteContent,type PublicProduct} from '@/lib/site-content';
import AnimatedAmount from './animated-amount';
import Reports from './reports';
import Premium from './premium';
import { supabase } from '@/lib/supabase';
import { empty, categories, loadData, saveItem, deleteItem, type Data } from '@/lib/store';
import { rupiah, today, summary, spent, safeToSpend, averageIncome, type Transaction, type Budget, type Goal, type Profile } from '@/lib/finance';
const nav=[{id:'dashboard',name:'Ringkasan',icon:LayoutDashboard},{id:'transactions',name:'Transaksi',icon:ArrowLeftRight},{id:'budget',name:'Budget',icon:ChartPie},{id:'goals',name:'Target',icon:Target},{id:'reports',name:'Laporan',icon:TrendingUp},{id:'premium',name:'Paket',icon:ShieldCheck},{id:'settings',name:'Pengaturan',icon:Settings}];
const profileDefault:Profile={name:'',purpose:'Mengatur pengeluaran',pattern:'Freelance/tidak tetap',fixed:0,project:20000,projects:4,opening:0};
const transactionSchema=z.object({amount:z.coerce.number().int().positive().max(1000000000000),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v&&v<=today()),description:z.string().max(180),category:z.enum(categories as [string,...string[]]),type:z.enum(['income','expense'])});
export default function BudgetApp({site}:{site:{content:SiteContent;products:PublicProduct[]}}){
 const [data,setData]=useState<Data>(empty),[user,setUser]=useState<string|null>(null),[page,setPage]=useState('dashboard'),[screen,setScreen]=useState('landing'),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<'transaction'|'budget'|'goal'|null>(null),[edit,setEdit]=useState<Transaction|Budget|Goal|null>(null),[month,setMonth]=useState(today().slice(0,7)),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 const notify=(text:string)=>{setMessage(text);setTimeout(()=>setMessage(''),3500);};
 useEffect(()=>{const location=new URLSearchParams(window.location.search);if(location.get('auth')==='register')setScreen('register');else if(location.get('auth')==='login')setScreen('login');if(location.get('view')==='premium')setPage('premium');let active=true;const open=async(id:string)=>{try{const d=await loadData(id);if(active){setData(d);setUser(id);setScreen(d.profile?'app':'onboarding');}}catch(e){setError((e as Error).message);}finally{setLoading(false);}};if(!supabase){setLoading(false);}else{void supabase.auth.getSession().then(({data:{session}})=>{if(session)void open(session.user.id);else setLoading(false);});const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')setScreen('password');else if(session)void open(session.user.id);else{setUser(null);setData(empty);setScreen('landing');}});return()=>{active=false;subscription.unsubscribe();};}},[]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(screen==='app'&&e.key==='n'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)&&!(e.target instanceof HTMLSelectElement)){e.preventDefault();setEdit(null);setModal('transaction');}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[screen]);
 async function demo(){setLoading(true);try{const d=await loadData('demo');setData(d);setUser('demo');setScreen(d.profile?'app':'onboarding');}catch{setError('Data lokal tidak dapat dibaca. Hapus penyimpanan situs lalu coba lagi.');}finally{setLoading(false);}}
 function commit(next:Data){if(!supabase||user==='demo')localStorage.setItem('mybudget-demo',JSON.stringify(next));setData(next);}
 async function save(table:'profiles'|'transactions'|'budgets'|'goals',item:Profile|Transaction|Budget|Goal){setBusy(true);setError('');const before=data;if(table==='transactions'){setData({...data,transactions:[...data.transactions.filter(t=>t.id!==(item as Transaction).id),item as Transaction]});}try{await saveItem(user!,table,item);if(table==='profiles'){commit({...data,profile:item as Profile});setScreen('app');}else{const list=data[table] as (Transaction|Budget|Goal)[];commit({...data,[table]:[...list.filter(v=>v.id!==(item as Transaction).id),item]});}setModal(null);notify('Berhasil disimpan.');}catch(e){setData(before);setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(table:'transactions'|'budgets'|'goals',id:string){setBusy(true);try{await deleteItem(user!,table,id);commit({...data,[table]:data[table].filter(v=>v.id!==id)});notify('Data dihapus.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){await fetch('/api/admin/session',{method:'DELETE'}).catch(()=>{});if(supabase)await supabase.auth.signOut();setUser(null);setData(empty);setScreen('landing');}
 const current=summary(data.transactions,data.profile?.opening||0,month),allocation=data.goals.filter(g=>g.saved<g.target).reduce((s,g)=>s+g.monthly,0),average=averageIncome(data.transactions,month),activeBudgets=data.budgets.filter(b=>b.month===month),remaining=activeBudgets.reduce((s,b)=>s+b.amount-spent(data.transactions,b.category,month),0);
 const totalBudget=activeBudgets.reduce((s,b)=>s+b.amount,0);
 const open=(type:'transaction'|'budget'|'goal',item:Transaction|Budget|Goal|null=null)=>{setError('');setEdit(item);setModal(type);};
 if(loading)return <div className="loading-shell"><Wordmark/><div className="skeleton"/><p>Menyiapkan keuanganmu…</p></div>;
 return <>{screen==='landing'?<Landing content={site.content} products={site.products} start={()=>setScreen('register')} login={()=>setScreen('login')} demo={demo}/>:['login','register','reset','password'].includes(screen)?<Auth screen={screen} change={setScreen} notify={notify}/>:screen==='onboarding'?<div className="onboarding"><Wordmark/><ProfileForm profile={data.profile||profileDefault} save={p=>save('profiles',p)} busy={busy} onboarding/><button className="text-button" onClick={logout}>Kembali</button></div>:<div className="app-shell">
 <aside className="sidebar"><Wordmark/><div className="workspace-label">RUANG KEUANGANMU</div><nav>{nav.map(n=><button aria-label={n.name} title={n.name} key={n.id} className={page===n.id?'nav-item active':'nav-item'} onClick={()=>setPage(n.id)}><n.icon size={19}/><span>{n.name}</span>{page===n.id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-tip"><ShieldCheck size={21}/><strong>Satu langkah kecil,<br/>lebih dekat ke tujuan.</strong><p>Catat rutin. Kenali polanya.</p></div><button className="account" onClick={()=>setPage('settings')}><span className="avatar">{data.profile?.name.slice(0,1).toUpperCase()}</span><span><strong>{data.profile?.name}</strong><small>Paket akun</small></span><Settings size={16}/></button><button className="logout" onClick={logout}><LogOut size={16}/>Keluar</button></aside>
 <main className="main"><header className="topbar"><span>Keuangan pribadi <ChevronRight size={14}/> {nav.find(n=>n.id===page)?.name}</span><span className="topbar-right"><span className="status-dot"/>{supabase&&user!=='demo'?'Tersambung':'Demo lokal'}<span className="avatar small">{data.profile?.name.slice(0,1).toUpperCase()}</span></span></header>
 {(!supabase||user==='demo')&&<div className="demo-banner">Mode demo · Data disimpan di browser ini. Belum terhubung ke akun Supabase.<button onClick={()=>{commit(empty);setScreen('onboarding');}}>Mulai ulang</button></div>}
 <div className="content"><div className="page-heading"><div><div className="eyebrow">{page==='dashboard'?'GAMBAR BESAR, LANGKAH KECIL':'RUANG KEUANGANMU'}</div><h1>{page==='dashboard'?`Halo, ${data.profile?.name.split(' ')[0]}.`:nav.find(n=>n.id===page)?.name}</h1><p>{page==='dashboard'?'Lihat posisi uangmu. Tentukan langkah selanjutnya.':page==='transactions'?'Setiap catatan membuat gambaranmu lebih jelas.':page==='budget'?'Beri setiap kebutuhan ruang yang cukup.':page==='goals'?'Target besar dimulai dari kebiasaan kecil.':page==='reports'?'Kenali pola pemasukan dan pengeluaranmu.':page==='premium'?'Pilih ruang yang sesuai dengan kebutuhanmu.':'Sesuaikan ruang ini dengan kebutuhanmu.'}</p></div><div className="heading-actions">{!['settings','reports','premium'].includes(page)&&<label className="month-input"><span className="sr-only">Bulan</span><input type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label>}<button className="button primary" onClick={()=>open('transaction')}><Plus size={17}/>Tambah transaksi <kbd>N</kbd></button></div></div>
 {page==='dashboard'&&<><div className="overview"><section className="balance-panel"><div className="balance-top"><span>Saldo saat ini</span><span className="pill">Saldo aktual</span></div><div className="balance-value"><AnimatedAmount value={current.balance}/></div><p>Uang yang tercatat, termasuk saldo awal.</p><div className="balance-divider"/><div className="balance-stats"><div><span><ArrowDownLeft size={16}/>Pemasukan bulan ini</span><strong>{rupiah(current.income)}</strong></div><div><span><ArrowUpRight size={16}/>Pengeluaran bulan ini</span><strong>{rupiah(current.expense)}</strong></div></div></section><section className="safe-panel"><div className="section-icon"><ShieldCheck size={21}/></div><span className="muted">Aman dibelanjakan</span><h2 className="money">{rupiah(safeToSpend(data.transactions,data.budgets,data.goals,data.profile?.opening||0,month))}</h2><p>Sisakan ruang untuk kebutuhan dan targetmu.</p><details><summary>Lihat perhitungan</summary><p>Saldo aktual − sisa budget wajib (minimal nol per kategori) − rencana alokasi target bulan ini. Alokasi belum memindahkan uang dan tidak mengurangi saldo aktual.</p></details></section></div>
 <div className="support-strip"><div><span>Budget tersisa</span><strong className={remaining<0?'danger money':'money'}>{rupiah(remaining)}</strong><small>{activeBudgets.length} kategori direncanakan</small></div><div><span>Rencana tabungan</span><strong className="money">{rupiah(allocation)}</strong><small>Alokasi target per bulan</small></div><div><span>Patokan pemasukan</span><strong className="money">{rupiah(average)}</strong><small>Rata-rata 3 bulan selesai</small></div></div>
 {data.profile?.pattern!=='Penghasilan tetap'&&average>0&&current.income<average*.6&&<div className="notice">Pemasukan bulan ini masih di bawah 60% rata-rata tiga bulan terakhir. Bulan ini mungkin belum selesai; sesuaikan rencana jika diperlukan.</div>}
 <div className="dashboard-grid"><section className="panel cashflow"><div className="section-heading"><div><h2>Arus kas bulan ini</h2><p>Pemasukan dan pengeluaran aktual.</p></div></div><div className="balance-stats"><div><span>Pemasukan (+)</span><strong className="money">+{rupiah(current.income)}</strong></div><div><span>Pengeluaran (−)</span><strong className="money">−{rupiah(current.expense)}</strong></div></div><button className="button secondary" style={{marginTop:24}} onClick={()=>setPage('reports')}>Buka Laporan Premium</button></section><section className="panel budget-preview"><div className="section-heading"><h2>Jaga batasmu</h2><button className="icon-button" aria-label="Buka budget" onClick={()=>setPage('budget')}><ArrowUpRight size={19}/></button></div>{activeBudgets.length?activeBudgets.slice(0,3).map(b=><BudgetRow key={b.id} budget={b} used={spent(data.transactions,b.category,month)}/>):<Empty title="Belum ada budget bulan ini." text="Mulai dari kebutuhan wajibmu." action={()=>open('budget')} label="Atur budget"/>}<div className="budget-footer"><span>Total rencana</span><strong className="money">{rupiah(totalBudget)}</strong></div></section></div>
 <div className="dashboard-grid bottom-grid"><section className="panel"><div className="section-heading"><h2>Transaksi terbaru</h2><button className="text-button" onClick={()=>setPage('transactions')}>Lihat semua <ArrowRight size={14}/></button></div>{data.transactions.length?data.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4).map(t=><TransactionRow key={t.id} t={t}/>):<Empty title="Belum ada transaksi." text="Project Rp20.000 pun layak dicatat." action={()=>open('transaction')} label="Tambah catatan pertama"/>}</section><section className="panel"><div className="section-heading"><h2>Targetmu</h2><button className="icon-button" aria-label="Buka target" onClick={()=>setPage('goals')}><ArrowUpRight size={19}/></button></div>{data.goals.length?data.goals.slice(0,2).map(g=><GoalRow key={g.id} goal={g}/>):<Empty title="Apa yang ingin kamu capai?" text="Beri nama targetmu dan mulai pelan-pelan." action={()=>open('goal')} label="Buat target"/>}</section></div><div className="insight-line"><TrendingUp size={20}/><p><strong>Perkiraan bukan pemasukan.</strong> Profilmu memperkirakan {rupiah((data.profile?.fixed||0)+(data.profile?.project||0)*(data.profile?.projects||0))}/bulan. Saldo hanya memakai transaksi aktual.</p></div></>}
 {page==='transactions'&&<section className="panel"><div className="filters"><label className="search"><Search size={18}/><span className="sr-only">Cari transaksi</span><input placeholder="Cari deskripsi atau kategori…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Jenis transaksi" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua jenis</option><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select></div>{data.transactions.filter(t=>t.date.startsWith(month)&&(filter==='all'||t.type===filter)&&`${t.description} ${t.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)).map(t=><TransactionRow key={t.id} t={t} actions={<><button aria-label="Edit transaksi" className="icon-button" onClick={()=>open('transaction',t)}><Pencil size={16}/></button><button disabled={busy} aria-label="Hapus transaksi" className="icon-button" onClick={()=>remove('transactions',t.id)}><Trash2 size={16}/></button></>}/>)}{!data.transactions.some(t=>t.date.startsWith(month)&&(filter==='all'||t.type===filter)&&`${t.description} ${t.category}`.toLowerCase().includes(query.toLowerCase()))&&<Empty title="Belum ada catatan yang cocok." text="Ubah filter atau catat transaksi untuk bulan ini." action={()=>open('transaction')} label="Tambah transaksi"/>}</section>}
 {page==='budget'&&<><div className="section-heading"><h2>Rencana {month}</h2><button className="button secondary" onClick={()=>open('budget')}><Plus size={17}/>Tambah budget</button></div><section className="panel">{activeBudgets.map(b=><div className="editable-row" key={b.id}><BudgetRow budget={b} used={spent(data.transactions,b.category,month)}/><div className="row-actions"><button className="icon-button" aria-label="Edit budget" onClick={()=>open('budget',b)}><Pencil size={16}/></button><button className="icon-button" disabled={busy} aria-label="Hapus budget" onClick={()=>remove('budgets',b.id)}><Trash2 size={16}/></button></div></div>)}{!activeBudgets.length&&<Empty title="Belum ada budget bulan ini." text="Tentukan batas untuk kategori pengeluaranmu." action={()=>open('budget')} label="Buat budget"/>}</section>{data.transactions.some(t=>t.type==='expense'&&t.date.startsWith(month)&&!activeBudgets.some(b=>b.category===t.category))&&<div className="notice">Ada pengeluaran tanpa budget: {[...new Set(data.transactions.filter(t=>t.type==='expense'&&t.date.startsWith(month)&&!activeBudgets.some(b=>b.category===t.category)).map(t=>t.category))].join(', ')}. Pengeluaran ini tetap masuk saldo.</div>}</>}
 {page==='goals'&&<><div className="section-heading"><h2>Pelan-pelan, tetap maju</h2><button className="button secondary" onClick={()=>open('goal')}><Plus size={17}/>Buat target</button></div><div className="goal-grid">{data.goals.map(g=><section className="panel" key={g.id}><GoalRow goal={g}/><p className="muted">Rencana {rupiah(g.monthly)}/bulan. Proyeksi mengasumsikan alokasi konsisten tanpa bunga.</p><div className="row-actions"><button className="button secondary" onClick={()=>open('goal',g)}><Pencil size={16}/>Edit progres</button><button disabled={busy} className="icon-button" aria-label="Hapus target" onClick={()=>remove('goals',g.id)}><Trash2 size={16}/></button></div></section>)}</div>{!data.goals.length&&<section className="panel"><Empty title="Belum ada target tabungan." text="Mulai dengan satu hal yang penting untukmu." action={()=>open('goal')} label="Buat target pertama"/></section>}<div className="insight-line"><Target size={20}/><p>Progres tabungan adalah catatan alokasi dari saldo yang ada. Tidak membuat transaksi dan tidak mengurangi saldo lagi.</p></div></>}
 {page==='reports'&&<Reports user={user!} month={month} onMonthChange={setMonth} add={()=>open('transaction')} upgrade={()=>setPage('premium')}/>}
 {page==='premium'&&<Premium user={user!} reports={()=>setPage('reports')}/>}
 {page==='settings'&&<><section className="panel"><h2>Butuh bantuan?</h2><SupportLink/></section><section className="panel profile-panel"><ProfileForm profile={data.profile!} save={p=>save('profiles',p)} busy={busy}/></section><section className="panel profile-panel"><div className="section-heading"><h2>Keamanan akun</h2><button className="text-button" onClick={logout}><LogOut size={16}/>Keluar</button></div>{supabase?<AccountSettings notify={notify}/>:<p className="muted">Email dan password tersedia setelah Supabase dikonfigurasi. Demo tidak membuat akun sungguhan.</p>}</section></>}
 <div className="review-account-link"><a className="text-button" href="/reviews">Tulis ulasan tentang My Budget <ArrowRight size={14}/></a></div><footer className="app-footer">My Budget <span>Pahami uangmu. Atur keuanganmu. Capai targetmu.</span></footer></div></main>{page==='dashboard'&&user&&user!=='demo'&&<SupportLink floating/>}<nav className="bottom-nav">{nav.map(n=><button className={page===n.id?'active':''} key={n.id} onClick={()=>setPage(n.id)}><n.icon size={20}/><span>{n.name}</span></button>)}</nav>{!['reports','premium'].includes(page)&&<button className="fab" aria-label="Tambah transaksi" onClick={()=>open('transaction')}><Plus/></button>}
 </div>}
 <Dialog.Root open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal(null);}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="modal"><Dialog.Title>{modal==='transaction'?(edit?'Edit transaksi':'Catat transaksi'):modal==='budget'?'Atur budget':'Target tabungan'}</Dialog.Title><Dialog.Description className="muted">{modal==='transaction'?'Nominal kecil juga berarti. Catat dengan jujur.':'Rencana yang realistis lebih mudah dijalankan.'}</Dialog.Description><Dialog.Close className="modal-close icon-button" disabled={busy} aria-label="Tutup"><X size={20}/></Dialog.Close>{modal&&<EntryForm key={`${modal}-${edit?.id}`} kind={modal} edit={edit} month={month} busy={busy} budgets={data.budgets} submit={item=>save(modal==='transaction'?'transactions':modal==='budget'?'budgets':'goals',item)}/>}</Dialog.Content></Dialog.Portal></Dialog.Root>
 {error&&<div role="alert" className="toast error-toast">{error}{error.includes('Batas Free')&&<button className="button secondary" onClick={()=>{setModal(null);setError('');setPage('premium');}}>Lihat paket</button>}<button aria-label="Tutup pesan" onClick={()=>setError('')}><X size={16}/></button></div>}{message&&<div role="status" className="toast"><Check size={18}/>{message}</div>}</>;
}
function Empty({title,text,action,label}:{title:string;text:string;action:()=>void;label:string}){return <div className="empty"><strong>{title}</strong><p>{text}</p><button className="text-button" onClick={action}>{label}<ArrowRight size={15}/></button></div>;}
function TransactionRow({t,actions}:{t:Transaction;actions?:React.ReactNode}){return <div className="transaction-row"><span className={`transaction-icon ${t.type}`}>{t.type==='income'?<ArrowDownLeft size={19}/>:<ArrowUpRight size={19}/>}</span><div className="transaction-info"><strong>{t.description||t.category}</strong><span>{t.origin==='recurring'?'Berulang · ':''}{t.category} · {new Date(t.date+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</span></div><strong className={`money transaction-amount ${t.type==='income'?'positive':''}`}>{t.type==='income'?'+':'−'}{rupiah(t.amount)}</strong>{actions&&<div className="row-actions">{actions}</div>}</div>;}
function EntryForm({kind,edit,month,busy,budgets,submit}:{kind:string;edit:Transaction|Budget|Goal|null;month:string;busy:boolean;budgets:Budget[];submit:(item:Transaction|Budget|Goal)=>void}){
 const [type,setType]=useState((edit as Transaction)?.type||'expense'),[category,setCategory]=useState((edit as Transaction|Budget)?.category||'Makan & minum'),[validation,setValidation]=useState('');
 const {register,handleSubmit}=useForm<Record<string,string>>();
 const onSubmit=(v:Record<string,string>)=>{setValidation('');const id=edit?.id||crypto.randomUUID();if(kind==='transaction'){const parsed=transactionSchema.safeParse({...v,type,category});if(!parsed.success){setValidation('Periksa nominal positif (rupiah bulat), kategori, deskripsi maksimal 180 karakter, dan tanggal valid yang tidak di masa depan.');return;}submit({id,...parsed.data});}else if(kind==='budget'){const amount=Number(v.amount);if(!Number.isSafeInteger(amount)||amount<=0||amount>1e12||!/^\d{4}-\d{2}$/.test(v.month)||Number(v.month.slice(5))<1||Number(v.month.slice(5))>12){setValidation('Isi batas positif dan bulan yang valid.');return;}if(budgets.some(b=>b.id!==id&&b.category===category&&b.month===v.month)){setValidation('Kategori ini sudah memiliki budget untuk bulan tersebut. Edit budget yang ada.');return;}submit({id,category,amount,month:v.month,mandatory:Boolean(v.mandatory)});}else{const target=Number(v.target),saved=Number(v.saved),monthly=Number(v.monthly);if(!v.name.trim()||v.name.length>80||![target,saved,monthly].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=1e12)||target===0){setValidation('Isi nama maksimal 80 karakter, target positif, dan nominal lainnya minimal nol.');return;}submit({id,name:v.name.trim(),target,saved,monthly});}};
 return <form onSubmit={handleSubmit(onSubmit)} className="form">{kind==='transaction'&&<div className="segmented"><button type="button" className={type==='expense'?'selected':''} onClick={()=>{setType('expense');setCategory('Makan & minum');}}>Pengeluaran</button><button type="button" className={type==='income'?'selected':''} onClick={()=>{setType('income');setCategory('Project');}}>Pemasukan</button></div>}{kind!=='goal'?<label>Nominal (Rp)<input autoFocus inputMode="numeric" type="number" step="1" min="1" required className="amount-field" placeholder="20.000" defaultValue={(edit as Transaction|Budget)?.amount} {...register('amount')}/></label>:<><label>Nama target<input autoFocus required maxLength={80} defaultValue={(edit as Goal)?.name} {...register('name')}/></label><label>Nominal target (Rp)<input required type="number" min="1" max="1000000000000" defaultValue={(edit as Goal)?.target} {...register('target')}/></label><div className="form-grid"><label>Sudah terkumpul (Rp)<input type="number" min="0" required defaultValue={(edit as Goal)?.saved||0} {...register('saved')}/></label><label>Alokasi bulanan (Rp)<input type="number" min="0" required defaultValue={(edit as Goal)?.monthly||0} {...register('monthly')}/></label></div></>}{kind!=='goal'&&<fieldset><legend>Kategori</legend><div className="chips">{categories.filter(c=>kind==='budget'||type==='expense'?!['Project','Gaji'].includes(c):['Project','Gaji','Lainnya'].includes(c)).map(c=><button type="button" aria-pressed={category===c} className={category===c?'selected':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div></fieldset>}{kind==='transaction'&&<><label>Deskripsi <span className="muted">(opsional)</span><input maxLength={180} defaultValue={(edit as Transaction)?.description} placeholder="Misalnya: desain untuk klien" {...register('description')}/></label><label>Tanggal<input required type="date" max={today()} defaultValue={(edit as Transaction)?.date||today()} {...register('date')}/></label></>}{kind==='budget'&&<><label>Bulan<input required type="month" defaultValue={(edit as Budget)?.month||month} {...register('month')}/></label><label className="checkbox"><input type="checkbox" defaultChecked={(edit as Budget)?.mandatory??true} {...register('mandatory')}/>Kebutuhan wajib (disisihkan dari aman dibelanjakan)</label></>}{validation&&<p role="alert" className="form-error">{validation}</p>}<button className="button primary full" disabled={busy}>{busy?'Menyimpan…':'Simpan'}</button></form>;
}
function ProfileForm({profile,save,busy,onboarding=false}:{profile:Profile;save:(p:Profile)=>void;busy:boolean;onboarding?:boolean}){const [pattern,setPattern]=useState(profile.pattern),[error,setError]=useState('');const {register,handleSubmit}=useForm<Record<string,string>>();return <form className="form" onSubmit={handleSubmit(v=>{const p={name:v.name.trim(),purpose:v.purpose,pattern,fixed:pattern==='Freelance/tidak tetap'?0:Number(v.fixed||0),project:pattern==='Penghasilan tetap'?0:Number(v.project||0),projects:pattern==='Penghasilan tetap'?0:Number(v.projects||0),opening:Number(v.opening||0)};if(!p.name||p.name.length>60||![p.fixed,p.project,p.projects,p.opening].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=1e12)||p.projects>1000){setError('Periksa nama dan nominal. Gunakan rupiah bulat minimal nol, jumlah project maksimal 1.000.');return;}save(p);})}><div><div className="eyebrow">{onboarding?'MULAI DARI KONDISIMU':'PROFIL & RENCANA'}</div><h2>{onboarding?'Kenalan dengan uangmu.':'Pengaturan keuangan'}</h2><p className="muted">{onboarding?'Tidak perlu angka sempurna. Kamu bisa mengubahnya nanti.':'Perkiraan membantu merencanakan, tidak dihitung sebagai saldo aktual.'}</p></div><label>Nama panggilan<input autoComplete="given-name" required maxLength={60} defaultValue={profile.name} {...register('name')}/></label><label>Tujuan utama<select defaultValue={profile.purpose} {...register('purpose')}>{['Mengatur pengeluaran','Menabung','Mengontrol budget','Mencapai target keuangan','Memahami kondisi keuangan'].map(v=><option key={v}>{v}</option>)}</select></label><label>Pola pemasukan<select value={pattern} onChange={e=>setPattern(e.target.value)}>{['Penghasilan tetap','Freelance/tidak tetap','Campuran'].map(v=><option key={v}>{v}</option>)}</select></label>{pattern!=='Freelance/tidak tetap'&&<label>Pemasukan tetap per bulan (Rp)<input type="number" min="0" defaultValue={profile.fixed} {...register('fixed')}/></label>}{pattern!=='Penghasilan tetap'&&<div className="form-grid"><label>Rata-rata per project (Rp)<input type="number" min="0" defaultValue={profile.project} {...register('project')}/></label><label>Project per bulan<input type="number" min="0" max="1000" defaultValue={profile.projects} {...register('projects')}/></label></div>}<label>Saldo awal sebelum pencatatan (Rp)<input type="number" min="0" defaultValue={profile.opening} {...register('opening')}/></label><p className="field-hint">Saldo awal adalah uang yang kamu miliki sebelum transaksi pertama. Jangan mencatatnya lagi sebagai pemasukan.</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Menyimpan…':onboarding?'Buka ruang keuanganku':'Simpan perubahan'}<ArrowRight size={16}/></button></form>;}
function Auth({screen,change,notify}:{screen:string;change:(s:string)=>void;notify:(s:string)=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!supabase){setError('Supabase belum dikonfigurasi. Gunakan demo di halaman utama.');return;}setBusy(true);const form=new FormData(e.currentTarget),email=String(form.get('email')||''),password=String(form.get('password')||'');try{const redirect=window.location.origin;const result=screen==='register'?await supabase.auth.signUp({email,password,options:{emailRedirectTo:redirect}}):screen==='reset'?await supabase.auth.resetPasswordForEmail(email,{redirectTo:redirect}):screen==='password'?await supabase.auth.updateUser({password}):await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(screen==='register')notify('Periksa email untuk konfirmasi akun.');if(screen==='reset')notify('Jika akun terdaftar, tautan reset dikirim ke email.');if(screen==='password'){notify('Password diperbarui.');change('app');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <div className="auth-layout"><div className="auth-story"><Wordmark/><h1>Ruang untuk<br/>uang dan<br/>rencanamu.</h1><p>Pemasukan tidak selalu sama.<br/>Keuangan tetap bisa terasa lebih jelas.</p><small>Track → Analyze → Plan → Act</small></div><div className="auth-card"><button className="text-button" onClick={()=>change('landing')}>← Kembali ke beranda</button><h2>{screen==='register'?'Mulai kebiasaan baru.':screen==='reset'?'Reset password':screen==='password'?'Password baru':'Selamat datang kembali.'}</h2><p className="muted">{screen==='register'?'Daftar gratis. Catat langkah pertamamu.':'Masuk ke ruang keuanganmu.'}</p><form className="form" onSubmit={submit}>{screen!=='password'&&<label>Email<input name="email" type="email" autoComplete="email" required/></label>}{screen!=='reset'&&<label>Password<input name="password" type="password" minLength={8} autoComplete={screen==='login'?'current-password':'new-password'} required/><small>Minimal 8 karakter.</small></label>}{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="button primary full">{busy?'Memproses…':screen==='register'?'Buat akun':screen==='reset'?'Kirim tautan reset':screen==='password'?'Simpan password':'Masuk'}</button></form><div className="auth-links"><button className="text-button" onClick={()=>change(screen==='register'?'login':'register')}>{screen==='register'?'Sudah punya akun? Masuk':'Belum punya akun? Daftar'}</button><button className="text-button" onClick={()=>change('reset')}>Lupa password?</button></div></div></div>;}
function AccountSettings({notify}:{notify:(s:string)=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <form className="form" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');const email=String(form.get('email')||''),password=String(form.get('password')||'');const {error}=await supabase!.auth.updateUser({...email?{email}:{},...password?{password}:{}});setBusy(false);if(error)setError(error.message);else notify('Permintaan disimpan. Konfirmasi perubahan email melalui tautan Supabase.');}}><label>Email baru<input name="email" type="email" autoComplete="email"/></label><label>Password baru<input name="password" type="password" minLength={8} autoComplete="new-password"/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button secondary" disabled={busy}>{busy?'Memproses…':'Perbarui keamanan'}</button></form>;}
