'use client';
import { useEffect,useState } from 'react';
import Image from 'next/image';
import { Clock,ShieldCheck } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { orderApi } from '@/lib/order-api';
import { orderStatus,validateProof,type Order } from '@/lib/checkout';
import { rupiah } from '@/lib/finance';
export default function Checkout({id}:{id:string}) {
 const demo=id==='demo';
 const [order,setOrder]=useState<Order|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[reference,setReference]=useState(''),[note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[qrisError,setQrisError]=useState(false),[proofUrl,setProofUrl]=useState('');
 useEffect(()=>{let alive=true;if(demo){setOrder({id:'demo',order_number:'CONTOH — BUKAN PESANAN',product_name:'Contoh Plus 30 hari',product_type:'subscription',price_rupiah:9900,unique_amount:0,total_rupiah:9900,duration_days:30,plan:'plus',merchant_name:'Belum ada merchant',qris_path:'',payment_instructions:'Tidak ada pembayaran dalam demo ini.',status:'pending',expires_at:new Date(Date.now()+24*3600000).toISOString(),created_at:new Date().toISOString(),review_note:null});setLoading(false);return;}async function load(){try{const r=await orderApi('/api/orders');const o=r.orders.find((o:Order)=>o.id===id);if(!o)throw new Error('Pesanan tidak ditemukan atau bukan milik akunmu.');if(alive)setOrder(o);}catch(e){if(alive)setError((e as Error).message);}finally{if(alive)setLoading(false);}}void load();const timer=setInterval(()=>{void load();},60000);return()=>{alive=false;clearInterval(timer);};},[id,demo]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!order)return;if(demo){const invalid=file?validateProof(file):null;if(invalid){setError(invalid);return;}setError('');setOrder({...order,status:'submitted'});return;}if(!supabase)return;setBusy(true);setError('');try{
  let path:string|null=null;
  if(file){const invalid=validateProof(file);if(invalid)throw new Error(invalid);const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sesi sudah berakhir. Masuk lagi.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];path=`${user.id}/${order.id}/${crypto.randomUUID()}.${ext}`;
   const upload=await supabase.storage.from('payment-proofs').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw new Error('Bukti gagal diunggah. Periksa tipe/ukuran dan akses pesanan.');
  }
  const r=await orderApi(`/api/orders/${order.id}/confirmation`,{reference,note,proof_path:path});setOrder(r.order);setFile(null);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function viewProof(){if(!supabase||!order)return;setError('');try{const r=await supabase.from('payment_confirmations').select('proof_path').eq('order_id',order.id).maybeSingle();if(r.error||!r.data?.proof_path)throw new Error('Tidak ada bukti gambar untuk pesanan ini.');const signed=await supabase.storage.from('payment-proofs').createSignedUrl(r.data.proof_path,60);if(signed.error)throw new Error('Bukti belum dapat dibuka.');setProofUrl(signed.data.signedUrl);setTimeout(()=>setProofUrl(''),60000);}catch(e){setError((e as Error).message);}}
 if(loading)return <section className="panel" role="status"><div className="skeleton review-skeleton"/>Memuat pesanan…</section>;
 return <div className="checkout-page">{demo&&<div className="demo-banner">Contoh alur checkout. Tidak membuat pesanan, mengunggah bukti, atau menerima pembayaran.</div>}{error&&<p role="alert" className="form-error">{error}</p>}{order&&<><section className="panel"><div className="section-heading"><div><span className="eyebrow">{order.order_number}</span><h1>{order.product_name}</h1></div><span className="pill">{orderStatus[order.status]}</span></div><span className="muted">{demo?'Nominal contoh':'Total yang harus dibayar'}</span><h2 className="money checkout-total">{rupiah(order.total_rupiah)}</h2>{order.unique_amount>0&&<p className="muted">Harga {rupiah(order.price_rupiah)} + nominal pencocokan {rupiah(order.unique_amount)}.</p>}<p className="muted">Masa akses: {order.duration_days} hari setelah pembayaran disetujui admin.</p><p className="checkout-deadline"><Clock size={16}/>Batas pembayaran: {new Date(order.expires_at).toLocaleString('id-ID')}</p></section>
 {order.status==='pending'&&<div className="checkout-columns"><section className="panel"><h2>QRIS merchant</h2><p className="muted">{order.merchant_name}</p>{demo?<div className="notice">QRIS resmi tidak ditampilkan pada contoh. Jangan melakukan pembayaran.</div>:qrisError?<p className="form-error">QRIS belum dapat ditampilkan. Jangan membayar sampai gambar tersedia.</p>:supabase&&<Image className="merchant-qris" src={supabase.storage.from('merchant-qris').getPublicUrl(order.qris_path).data.publicUrl} alt={`QRIS resmi ${order.merchant_name}`} width={320} height={400} unoptimized onError={()=>setQrisError(true)}/>}<p className="notice">{demo?'Contoh nominal '+rupiah(order.total_rupiah)+'. Tidak perlu memasukkan nominal atau membayar.':<>QRIS statis tidak memuat nominal. Masukkan tepat {rupiah(order.total_rupiah)} di aplikasi pembayaran.</>}</p><p className="payment-instructions">{order.payment_instructions}</p><p className="muted">Pastikan nama merchant sesuai. Tidak ada deteksi pembayaran otomatis.</p></section><section className="panel"><h2>Konfirmasi pembayaran</h2><p className="muted">{demo?'Gunakan referensi contoh. File pilihan tidak diunggah dan tidak ada pembayaran.':'Kirim hanya setelah membayar. Konfirmasi menunggu pemeriksaan admin dan tidak langsung membuka Premium.'}</p><form className="form" onSubmit={submit}><label>Referensi transaksi<input required minLength={3} maxLength={120} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Catatan (opsional)<textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><label>Bukti gambar (opsional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setProofUrl('');setFile(e.target.files?.[0]||null);}}/><small>JPG, PNG, WebP · maksimal 5 MB · disimpan privat.</small></label><button className="button primary" disabled={busy||qrisError}>{busy?'Mengirim…':demo?'Simulasikan konfirmasi':'Saya sudah membayar'}</button></form></section></div>}
 {order.status!=='pending'&&<section className="panel"><ShieldCheck size={24}/><h2>{orderStatus[order.status]}</h2><p className="muted">{demo?'Simulasi selesai. Tidak ada pesanan atau aktivasi Premium; status ini hanya contoh.':order.status==='submitted'?'Konfirmasi sudah diterima. Admin akan memeriksa transaksi yang masuk ke akun merchant sebelum mengaktifkan paket.':order.status==='expired'?'Pesanan ini tidak dapat dibayar lagi. Buka halaman Paket untuk membuat pesanan baru.':order.review_note||'Lihat status dan masa akses di halaman Paket.'}</p>{order.status==='submitted'&&!demo&&<><button className="button secondary" onClick={viewProof}>Lihat bukti saya (60 detik)</button>{proofUrl&&<Image src={proofUrl} alt="Bukti pembayaran privat milikmu" width={480} height={600} unoptimized className="private-proof"/>}</>}</section>}</>}</div>;
}
