'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {LockKeyhole} from 'lucide-react';import {supabase} from '@/lib/supabase';import {rupiah} from '@/lib/finance';import {plannerFields,plannerNames,type ToolKind,type PlannerResult} from '@/lib/finance/planners';
type Saved={id:string;title:string;inputs:Record<string,number>;created_at:string};
export default function DigitalPlanner({tool}:{tool:ToolKind}){const [inputs,setInputs]=useState<Record<string,number>>(()=>Object.fromEntries(plannerFields[tool].map(f=>[f.key,f.key==='months'?12:f.key==='reserveMonths'?3:0]))),[saved,setSaved]=useState<Saved[]>([]),[result,setResult]=useState<PlannerResult|null>(null),[title,setTitle]=useState('Rencana keuangan'),[locked,setLocked]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function request(body?:unknown){const session=(await supabase?.auth.getSession())?.data.session;if(!session){setLocked(true);setSaved([]);setResult(null);return null;}const r=await fetch(`/api/tools/${tool}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(r.status===403||r.status===401){setLocked(true);setSaved([]);setResult(null);return null;}if(!r.ok){const e=await r.json();throw new Error(e.error);}setLocked(false);return r;}
 useEffect(()=>{let alive=true;async function load(){try{const r=await request();if(r&&alive)setSaved((await r.json()).saved);}catch(e){if(alive)setError((e as Error).message);}finally{if(alive)setBusy(false);}}void load();window.addEventListener('focus',load);return()=>{alive=false;window.removeEventListener('focus',load);};},[tool]); // eslint-disable-line react-hooks/exhaustive-deps
 async function calculate(save=false,exportCsv=false){setBusy(true);setError('');setMessage('');try{const r=await request({inputs,title,save,export:exportCsv});if(r){if(exportCsv){const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`mybudget-${tool}-planner.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('CSV dibuat.');}else{const body=await r.json();setResult(body.result);if(save){setMessage('Rencana tersimpan.');const list=await request();if(list)setSaved((await list.json()).saved);}}}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(locked)return <section className="panel form"><LockKeyhole/><h1>{plannerNames[tool]}</h1><p>Susun rencana dari inputmu, simpan hasil, dan ekspor. Akses memerlukan pembelian produk ini yang sudah diverifikasi paid.</p><Link className="button primary" href="/?view=premium">Lihat produk dan checkout</Link><small>Pembayaran manual; pembelian hanya tersedia jika produk aktif dan QRIS resmi sudah dikonfigurasi.</small></section>;
 return <section className="panel form"><h1>{plannerNames[tool]}</h1><p className="muted">Perencanaan, bukan jaminan hasil. Input tidak otomatis mengambil data rekeningmu.</p>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<form className="form" onSubmit={e=>{e.preventDefault();void calculate();}}>{plannerFields[tool].map(f=><label key={f.key}>{f.label}<input type="number" required step={1} min={f.key==='months'||f.key==='reserveMonths'?1:0} max={f.max} value={inputs[f.key]} onChange={e=>{setInputs({...inputs,[f.key]:Number(e.target.value)});setResult(null);}}/></label>)}<button disabled={busy} className="button primary">{busy?'Memeriksa…':'Hitung rencana'}</button></form>{result&&<><h2>Hasil rencana</h2>{result.values.map(v=><div key={v.label}><span>{v.label}</span><strong className="money" style={{display:'block',fontSize:24}}>{v.value===null?'Belum dapat diperkirakan':v.unit==='rupiah'?rupiah(v.value):`${v.value} ${v.unit}`}</strong></div>)}<details open><summary>Asumsi</summary>{result.notes.map(n=><p key={n}>{n}</p>)}</details><label>Nama rencana<input maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="chips"><button disabled={busy} className="button primary" onClick={()=>calculate(true)}>Simpan rencana</button><button disabled={busy} className="button secondary" onClick={()=>calculate(false,true)}>Ekspor CSV</button></div></>}<h2>Rencana tersimpan</h2>{!busy&&!saved.length&&<p>Belum ada rencana tersimpan. Hitung lalu simpan rencana pertamamu.</p>}{saved.map(s=><button key={s.id} disabled={busy} className="button secondary" onClick={()=>{setInputs(s.inputs);setTitle(s.title);setResult(null);setMessage('Rencana dimuat. Klik Hitung rencana untuk melihat hasil.');}}>{s.title} · {new Date(s.created_at).toLocaleDateString('id-ID')}</button>)}</section>;
}
