'use client';
import {useEffect,useState} from 'react';
import {Star} from 'lucide-react';
import {orderApi} from '@/lib/order-api';
import {supabase} from '@/lib/supabase';
import {reviewSchema} from '@/lib/reviews';
export default function OrderReview({order}:{order:string}){
 const [name,setName]=useState(''),[body,setBody]=useState(''),[rating,setRating]=useState(0),[status,setStatus]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;void (async()=>{try{const r=await orderApi(`/api/reviews?order=${order}`);if(!alive)return;if(r.review){setName(r.review.display_name);setBody(r.review.body);setRating(r.review.rating);setStatus(r.review.status);}else if(supabase){const u=await supabase.auth.getUser();const p=await supabase.from('profiles').select('data').eq('user_id',u.data.user?.id||'').maybeSingle();if(alive)setName(p.data?.data?.name||'');}}catch(e){if(alive)setError((e as Error).message);}finally{if(alive)setLoading(false);}})();return()=>{alive=false;};},[order]);
 async function save(e:React.FormEvent){e.preventDefault();setError('');const v=reviewSchema.safeParse({display_name:name,body,rating});if(!v.success){setError(v.error.issues[0].message);return;}setBusy(true);try{await orderApi('/api/reviews',{order_id:order,...v.data});setStatus('pending');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><h2>Beri Ulasan</h2><p className="muted">Satu ulasan per pesanan. Nama boleh disamarkan. Perubahan diperiksa kembali sebelum tampil publik.</p>{loading?<p role="status">Memuat ulasan…</p>:<form className="form" onSubmit={save}><fieldset><legend>Rating (wajib)</legend><div className="rating-picker">{[1,2,3,4,5].map(n=><button key={n} type="button" aria-label={`${n} bintang`} aria-pressed={rating===n} onClick={()=>setRating(n)}><Star size={24} fill={n<=rating?'currentColor':'none'}/></button>)}</div></fieldset><label>Nama tampilan<input required minLength={2} maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="Ak***a"/></label><label>Komentar<textarea required minLength={10} maxLength={500} value={body} onChange={e=>setBody(e.target.value)} rows={4}/><small>{body.length}/500 · Jangan tulis data pribadi atau keuangan.</small></label><button className="button primary" disabled={busy}>{busy?'Menyimpan…':status?'Perbarui ulasan':'Kirim ulasan'}</button></form>}{status&&<p role="status">{status==='pending'?'Menunggu persetujuan admin.':status==='approved'?'Ulasan sudah tampil publik.':'Ulasan disembunyikan. Kamu dapat memperbaikinya.'}</p>}{error&&<p className="form-error" role="alert">{error}</p>}</section>;
}
