'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ShieldCheck } from 'lucide-react';
import { getEntitlement, type Entitlement } from '@/lib/entitlements';
import { supabase } from '@/lib/supabase';
import { rupiah } from '@/lib/finance';
import Purchases from './purchases';
type Plan = {code:string;name:string;price_rupiah:number;duration_days:number|null;transactions_limit:number|null;categories_limit:number|null;goals_limit:number|null;budgets_limit:number|null;reports_access:boolean};
const limitLabel = (limit:number|null, unit:string) => limit === null ? `${unit} tanpa batas` : `${limit} ${unit}`;
export default function Premium({ user, reports }: {user:string;reports:()=>void}) {
 const [plans,setPlans]=useState<Plan[]>([]),[entitlement,setEntitlement]=useState<Entitlement|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function exportCsv(){setError('');try{if(!supabase)throw new Error('Supabase belum tersedia.');const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Masuk untuk mengekspor transaksi.');const r=await fetch('/api/exports/transactions',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});if(!r.ok){const body=await r.json();throw new Error(body.error);}const url=URL.createObjectURL(await r.blob());const link=document.createElement('a');link.href=url;link.download='mybudget-transactions.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{let alive=true;async function load(){try{
  if(!supabase) return;
  const r=await supabase.from('plans').select('*').order('price_rupiah');
  if(r.error) throw new Error('Katalog belum tersedia. Terapkan migration 004 lalu coba lagi.');
  const e=user==='demo'?null:await getEntitlement();
  if(alive){setPlans(r.data||[]);setEntitlement(e);}
 }catch(e){if(alive)setError((e as Error).message);}finally{if(alive)setLoading(false);}}void load();const recheck=()=>{void load();};window.addEventListener('focus',recheck);const timer=setInterval(recheck,60000);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',recheck);};},[user]);
 return <div className="package-page"><section className="panel package-status"><ShieldCheck size={24}/><div><h2>{entitlement?`Paketmu: ${entitlement.name}`:user==='demo'?'Demo · akses Laporan terkunci':'Paket akun'}</h2><p className="muted">{entitlement?.expires_at?`Aktif sampai ${new Date(entitlement.expires_at).toLocaleString('id-ID')}.`:'Paket Free berlaku tanpa batas waktu. Premium kedaluwarsa kembali ke Free; data tetap tersimpan.'}</p></div>{entitlement?.reports_access&&<button className="button secondary" onClick={reports}>Buka Laporan</button>}</section>
 {loading&&<div className="skeleton review-skeleton" role="status" aria-label="Memuat paket"/>}{error&&<p className="form-error" role="alert">{error}</p>}
 <div className="package-grid">{plans.map(p=><section className="panel" key={p.code}><span className="eyebrow">{p.name}</span><h2 className="money">{rupiah(p.price_rupiah)}{p.duration_days&&<small>/{p.duration_days} hari</small>}</h2><ul><li>{limitLabel(p.transactions_limit,'transaksi per bulan')}</li><li>{limitLabel(p.categories_limit,'kategori kustom')}</li><li>{limitLabel(p.goals_limit,'target aktif')}</li><li>{limitLabel(p.budgets_limit,'kategori budget per bulan')}</li><li>{p.reports_access?'Laporan Premium':'Laporan Premium terkunci'}</li></ul><span className="pill">{p.code===entitlement?.plan?'Paket aktif':p.code==='free'?'Paket dasar':'Aktivasi belum tersedia'}</span></section>)}</div>
 <section className="panel"><h2>Ekspor transaksi</h2><p className="muted">CSV tersedia untuk Plus/Pro aktif. File dibuat di server dan hanya memuat transaksi milikmu.</p><button className="button secondary" disabled={!entitlement?.reports_access||user==='demo'} onClick={exportCsv}>Unduh CSV</button></section><Purchases user={user}/><section className="panel"><h2>Pilih sesuai kebutuhanmu.</h2><p className="muted">Aktivasi membutuhkan pembayaran yang benar-benar diterima merchant dan diverifikasi admin. Pengiriman konfirmasi tidak membuka Premium.</p><p className="muted">Transaksi berulang tersedia untuk Plus/Pro. Financial health, forecast, goal projection, insights dan laporan lanjutan sedang diverifikasi; statusnya belum dinyatakan tersedia penuh. Analitik lanjutan dan tools interaktif: segera hadir.</p><nav className='chips' aria-label='Analitik Pro'><Link className='button secondary' href='/features/recurring'>Transaksi berulang</Link><Link className='button secondary' href='/features/insights'>Advanced insights</Link><Link className='button secondary' href='/features/reports'>Advanced reports</Link><Link className='button secondary' href='/features/health'>Financial health</Link><Link className='button secondary' href='/features/forecast'>Forecast</Link><Link className='button secondary' href='/features/projection'>Goal projection</Link></nav></section></div>;
}
