'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {LockKeyhole} from 'lucide-react';import {supabase} from '@/lib/supabase';
import type {financialHealth} from '@/lib/finance/analytics';
import type {cashForecast} from '@/lib/finance/forecast';import {rupiah} from '@/lib/finance';
import {ResponsiveContainer,ComposedChart,Area,Line,XAxis,YAxis,Tooltip} from 'recharts';
import {goalProjection} from '@/lib/finance/projection';
type Result={health:ReturnType<typeof financialHealth>;forecast:ReturnType<typeof cashForecast>;projection:ReturnType<typeof goalProjection>;date:string};
export default function ProAnalytics({feature}:{feature:string}){
 const [result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[locked,setLocked]=useState(false),[loading,setLoading]=useState(true);
 const [override,setOverride]=useState<{id:string;monthly:number}|undefined>(),[saving,setSaving]=useState(false),[success,setSuccess]=useState('');
 async function confirm(){if(!override||!result)return;setSaving(true);setSuccess('');try{
  const session=(await supabase?.auth.getSession())?.data.session;if(!session)throw new Error('Masuk kembali untuk menyimpan.');
  const r=await fetch('/api/analytics',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({goal_id:override.id,allocation:override.monthly})});
  const body=await r.json();if(!r.ok){if(r.status===403){setResult(null);setLocked(true);}throw new Error(body.error);}
  const refresh=await fetch('/api/analytics',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});if(!refresh.ok){setResult(null);throw new Error('Alokasi tersimpan; muat ulang untuk memeriksa akses.');}setResult(await refresh.json());setOverride(undefined);setSuccess('Alokasi tersimpan.');
 }catch(e){setSuccess((e as Error).message);}finally{setSaving(false);}}
 useEffect(()=>{let alive=true;async function load(){try{
  const session=(await supabase?.auth.getSession())?.data.session;
  if(!session){if(alive){setResult(null);setLocked(true);}return;}
  const r=await fetch('/api/analytics',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});
  if(!alive)return;if(r.status===403||r.status===401){setResult(null);setLocked(true);return;}
  const body=await r.json();if(!r.ok)throw new Error(body.error);setResult(body);setLocked(false);setError('');
 }catch(e){if(alive){setResult(null);setError((e as Error).message);}}finally{if(alive)setLoading(false);}}
 void load();window.addEventListener('focus',load);const timer=setInterval(load,60000);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',load);};},[]);
 if(loading)return <div className="skeleton review-skeleton" role="status" aria-label="Memeriksa akses Pro"/>;
 if(locked)return <section className="panel form"><LockKeyhole/><h1>Kenali keuanganmu lebih dekat.</h1><p>Pro membuka financial health, perkiraan arus kas, dan simulasi target. Akses diperiksa di server.</p><Link href="/?view=premium" className="button primary">Upgrade ke Pro</Link></section>;
 if(error)return <p className="form-error" role="alert">{error}</p>;
 if(!result)return null;
 if(feature==='health')return <section className="panel form"><h1>Financial health</h1>{!result.health?<p>Data belum cukup. Catat minimal 2 bulan penuh, pemasukan, pengeluaran dan budget pada periode tersebut.</p>:<><div className="balance-value money">{result.health.score}<small>/100</small></div><p>{result.health.weakest.tip}</p><details><summary>Metode dan asumsi</summary><p>Periode {result.health.months.join(', ')}. Bulan kosong dihitung nol. Surplus bukan alokasi goal; skor merupakan ringkasan, bukan nasihat investasi.</p></details>{result.health.parts.map(p=><article key={p.name}><h2>{p.name} · {Math.round(p.score)}/100</h2><progress max={100} value={p.score} aria-label={p.name}/><p className="muted">Bobot {p.weight}% · {p.method}</p></article>)}</>}</section>;
 if(feature==='forecast')return <section className="panel form"><h1>Perkiraan arus kas</h1>{!result.forecast?<p>Data belum cukup. Lengkapi pencatatan minimal 3 bulan penuh. Bulan kosong tetap dihitung.</p>:<><p>Pengeluaran rencana per 30 hari: <strong className="money">{rupiah(result.forecast.expense)}</strong></p>{result.forecast.negativeDate&&<p className="form-error">Pada skenario hati-hati, saldo diperkirakan negatif mulai {result.forecast.negativeDate}. Pertimbangkan menambah cadangan atau meninjau budget.</p>}<div style={{height:280,width:'100%',minWidth:0}} role="img" aria-label="Rentang perkiraan saldo 90 hari. Rincian angka tersedia pada tabel."><ResponsiveContainer><ComposedChart data={result.forecast.points.map(p=>({...p,range:[p.careful,p.optimistic]}))}><XAxis dataKey="day" unit=" hari"/><YAxis tickFormatter={v=>rupiah(v)} width={90}/><Tooltip formatter={v=>Array.isArray(v)?v.map(n=>rupiah(Number(n))).join(' – '):rupiah(Number(v))}/><Area dataKey="range" name="Rentang hati-hati–optimis" fill="#dbeafe" stroke="#93c5fd" isAnimationActive={false}/><Line dataKey="realistic" name="Realistis" stroke="#2563eb" dot={false} isAnimationActive={false}/><Line dataKey="careful" name="Hati-hati" stroke="#475569" strokeDasharray="5 4" dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div><div style={{overflowX:'auto'}}><table><caption>Perkiraan saldo, bukan jaminan</caption><thead><tr><th>Hari</th><th>Hati-hati</th><th>Realistis</th><th>Optimis</th></tr></thead><tbody>{[30,60,90].map(day=>{const p=result.forecast!.points[day];return <tr key={day}><th>{day}</th><td className="money">{rupiah(p.careful)}</td><td className="money">{rupiah(p.realistic)}</td><td className="money">{rupiah(p.optimistic)}</td></tr>;})}</tbody></table></div><details><summary>Metode dan asumsi</summary><p>Periode {result.forecast.months.join(', ')}. Pemasukan: kuartil 25%, median, kuartil 75%; bukan perkiraan onboarding. Pengeluaran per kategori: nilai terbesar antara rata-rata aktual dan budget bulan ini, termasuk budget wajib. Saldo menyebar merata setiap 30 hari; tanggal negatif bukan jadwal pembayaran pasti. Aturan recurring belum tersedia dan tidak dimasukkan. Alokasi goal tidak mengurangi saldo aktual atau proyeksi ini.</p></details></>}</section>;
 if(feature==='projection'){const projection=goalProjection(result.projection.goals,result.date,result.projection.capacity,override);return <section className="panel form"><h1>Simulasi target</h1><p>Ubah alokasi untuk melihat perkiraan. Perubahan baru disimpan setelah dikonfirmasi.</p>{projection.competing&&<p className="muted">Total rencana {rupiah(projection.total)} melebihi surplus patokan {rupiah(projection.capacity||0)}. Perkiraan membagi dana secara proporsional antar target aktif.</p>}{!projection.goals.length&&<p>Belum ada target. <Link href="/?view=goals">Buat target pertama.</Link></p>}{projection.goals.map(g=><article key={g.id}><h2>{g.name}</h2><p className="money">{rupiah(g.saved)} dari {rupiah(g.target)}</p><label>Simulasi alokasi bulanan (Rp)<input type="number" min={0} max={1e12} step={1} value={override?.id===g.id?override.monthly:g.monthly} onChange={e=>{const value=Number(e.target.value);if(Number.isSafeInteger(value)&&value>=0&&value<=1e12){setOverride({id:g.id,monthly:value});setSuccess('');}}}/></label><p>{g.status==='achieved'?'Target sudah tercapai.':g.status==='zero'?'Tetapkan alokasi untuk membuat perkiraan.':g.status==='insufficient'?'Data belum cukup: catat minimal 2 bulan penuh.':g.status==='unfunded'?'Belum ada surplus historis untuk mendanai alokasi ini.':g.date?`Perkiraan tercapai ${g.date} (${g.months} bulan).`:'Perkiraan lebih dari 100 tahun; tinjau alokasi.'}</p>{g.status==='estimated'&&<small>Dana patokan untuk target ini: {rupiah(g.funded)}/bulan.</small>}</article>)}{override&&<div className="hero-actions"><button className="button primary" disabled={saving} onClick={confirm}>{saving?'Menyimpan…':'Konfirmasi alokasi'}</button><button className="button secondary" disabled={saving} onClick={()=>setOverride(undefined)}>Batalkan simulasi</button></div>}{success&&<p role="status">{success}</p>}<details><summary>Metode dan asumsi</summary><p>Patokan dana: median surplus bulanan aktual dari maksimal 6 bulan penuh terakhir, minimum 2 bulan; bulan kosong termasuk nol. Jika alokasi bersaing, dana dibagi sebanding rencana masing-masing. Hanya satu target disimulasikan sekaligus. Tabungan awal target sudah tercatat; perubahan alokasi tidak menjadi transaksi, tidak mengurangi saldo, dan tidak otomatis menambah progres. Perkiraan mengasumsikan alokasi efektif tetap setiap bulan, tanpa bunga. Tanggal akhir bulan disesuaikan.</p></details></section>;}
 return null;
}
