'use client';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { ArrowDownLeft, ArrowUpRight, ChartNoAxesCombined } from 'lucide-react';
import { report } from '@/lib/finance/reports';
import { rupiah, type Transaction } from '@/lib/finance';
const monthLabel = (month: string) => new Date(`${month}-01T12:00:00`).toLocaleDateString('id-ID', { month: 'short', year: '2-digit' });
export default function Reports({ transactions, month, add }: { transactions: Transaction[]; month: string; add: () => void }) {
 const r = report(transactions, month);
 return <div className="reports">
  <div className="report-summary"><div><span><ArrowDownLeft size={16}/> Pemasukan · {monthLabel(month)}</span><strong className="money">+{rupiah(r.current.income)}</strong><small>{r.incomeChange.label} dibanding bulan lalu</small></div><div><span><ArrowUpRight size={16}/> Pengeluaran · {monthLabel(month)}</span><strong className="money">−{rupiah(r.current.expense)}</strong><small>{r.expenseChange.label} dibanding bulan lalu</small></div></div>
  {!r.hasData ? <section className="panel review-empty"><ChartNoAxesCombined size={28}/><strong>Belum ada arus kas dalam enam bulan ini.</strong><p>Catat pemasukan atau pengeluaran pertama untuk melihat laporanmu.</p><button className="button primary" onClick={add}>Catat transaksi pertama</button></section> : <section className="panel"><div className="section-heading"><div><h2>Arus kas enam bulan</h2><p>Pemasukan dan pengeluaran aktual, tanpa saldo awal atau alokasi target.</p></div></div><div className="chart-legend"><span>■ Pemasukan (+)</span><span>▨ Pengeluaran (−)</span></div><div className="report-chart" role="img" aria-label="Grafik arus kas enam bulan. Nilai lengkap tersedia dalam tabel di bawah."><ResponsiveContainer width="100%" height="100%"><BarChart data={r.series} margin={{ left: 0, right: 8, top: 16 }}><defs><pattern id="report-expense" width="6" height="6" patternUnits="userSpaceOnUse"><rect width="6" height="6" fill="#64748b"/><path d="M0 6L6 0" stroke="#e2e8f0" strokeWidth="1.5"/></pattern></defs><XAxis dataKey="month" tickFormatter={monthLabel} tickLine={false} axisLine={false} tick={{ fontSize: 11 }}/><YAxis width={55} tickLine={false} axisLine={false} tick={{ fontSize: 10 }} tickFormatter={v => new Intl.NumberFormat('id-ID', { notation: 'compact' }).format(v)}/><Tooltip formatter={v => rupiah(Number(v))} labelFormatter={v => monthLabel(String(v))}/><Bar dataKey="income" name="Pemasukan (+)" fill="#2563eb" radius={[4,4,0,0]}/><Bar dataKey="expense" name="Pengeluaran (−)" fill="url(#report-expense)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><details className="report-table"><summary>Lihat angka per bulan</summary><table><caption className="sr-only">Arus kas enam bulan dalam rupiah</caption><thead><tr><th>Bulan</th><th>Pemasukan (+)</th><th>Pengeluaran (−)</th></tr></thead><tbody>{r.series.map(s => <tr key={s.month}><th>{monthLabel(s.month)}</th><td className="money">{rupiah(s.income)}</td><td className="money">{rupiah(s.expense)}</td></tr>)}</tbody></table></details></section>}
  <section className="panel"><div className="section-heading"><div><h2>Ke mana uangmu pergi?</h2><p>Kategori pengeluaran bulan {monthLabel(month)}, dari yang terbesar.</p></div></div>{!r.categories.length ? <div className="review-empty"><strong>Belum ada pengeluaran bulan ini.</strong><p>Catat yang pertama untuk melihat pembagiannya.</p><button className="button secondary" onClick={add}>Tambah pengeluaran</button></div> : <ol className="report-categories">{r.categories.map((c, i) => <li key={c.name}><span className="report-rank">{i+1}</span><div><div className="report-category-title"><strong>{c.name}</strong><span className="money">{rupiah(c.amount)}</span></div><div className="progress" role="progressbar" aria-label={`Porsi ${c.name}`} aria-valuenow={Math.round(c.share)} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${c.share}%`}}/></div><small>{new Intl.NumberFormat('id-ID', {maximumFractionDigits:1}).format(c.share)}% dari pengeluaran bulan ini</small></div></li>)}</ol>}</section>
  <p className="muted">Laporan sederhana tersedia untuk semua paket. Bulan berjalan belum selesai; perbandingan bukan prediksi. Laporan lanjutan: segera hadir.</p>
 </div>;
}
