'use client';
import { useEffect, useState } from 'react';
import { Star, MessageSquare, Check, Pencil } from 'lucide-react';
import { supabase as configuredSupabase } from '@/lib/supabase';
import { reviewSchema, type Review } from '@/lib/reviews';
export default function Reviews({onLogin,demo=false}:{onLogin?:()=>void;demo?:boolean}){
 const supabase=demo?null:configuredSupabase;
 const [reviews,setReviews]=useState<Review[]>([]),[own,setOwn]=useState<Review|null>(null),[user,setUser]=useState<string|null>(null),[filter,setFilter]=useState(0),[rating,setRating]=useState(0),[name,setName]=useState(''),[body,setBody]=useState(''),[consent,setConsent]=useState(false),[loading,setLoading]=useState(true),[unavailable,setUnavailable]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[stats,setStats]=useState({total:0,average:0,counts:[0,0,0,0,0]});
 async function refresh(){
  setUnavailable(false);
  if(!supabase){const stored:Review[]=JSON.parse(localStorage.getItem('mybudget-demo-review')||'[]');setReviews(stored);setOwn(stored[0]||null);setStats({total:stored.length,average:stored[0]?.rating||0,counts:[1,2,3,4,5].map(r=>stored.filter(v=>v.rating===r).length)});setLoading(false);return;}
  const {data:{session}}=await supabase.auth.getSession();setUser(session?.user.id||null);
  const [list,totals,mine]=await Promise.all([supabase.from('public_reviews').select('*').order('created_at',{ascending:false}).limit(20),supabase.rpc('review_summary'),session?supabase.from('reviews').select('*').eq('user_id',session.user.id).maybeSingle():Promise.resolve({data:null,error:null})]);
  if(list.error||totals.error||mine.error)throw new Error('Ulasan belum dapat dimuat. Coba lagi nanti.');
  setReviews(list.data||[]);setOwn(mine.data);const s=totals.data?.[0];setStats(s?{total:Number(s.total),average:Number(s.average),counts:s.counts.map(Number)}:{total:0,average:0,counts:[0,0,0,0,0]});setLoading(false);
 }
 useEffect(()=>{void refresh().catch(e=>{setError(e.message);setUnavailable(true);setLoading(false);});if(supabase){const {data:{subscription}}=supabase.auth.onAuthStateChange(()=>{setTimeout(()=>void refresh().catch(e=>{setError(e.message);setUnavailable(true);setLoading(false);}),0);});return()=>subscription.unsubscribe();}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setSuccess('');const result=reviewSchema.safeParse({display_name:name,rating,body});if(!result.success){setError(result.error.issues[0].message);return;}if(!consent){setError('Setujui penayangan nama dan ulasan sebelum mengirim.');return;}if(supabase&&!user){setError('Masuk terlebih dahulu untuk menulis ulasan.');return;}setBusy(true);try{
  if(supabase){const {error}=await supabase.from('reviews').upsert({user_id:user,...result.data},{onConflict:'user_id'});if(error)throw new Error('Ulasan gagal disimpan. Coba lagi setelah memeriksa koneksi.');}
  else{const timestamp=new Date().toISOString();localStorage.setItem('mybudget-demo-review',JSON.stringify([{id:own?.id||crypto.randomUUID(),...result.data,created_at:own?.created_at||timestamp,updated_at:timestamp}]));}
  await refresh();setSuccess(own?'Ulasan diperbarui.':'Terima kasih, ulasanmu berhasil disimpan.');setBody('');setRating(0);setConsent(false);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!own)return;setBusy(true);setError('');try{if(supabase){const {error}=await supabase.from('reviews').delete().eq('user_id',user!);if(error)throw new Error('Ulasan belum dapat dihapus. Coba lagi.');}else localStorage.removeItem('mybudget-demo-review');await refresh();setBody('');setName('');setRating(0);setConsent(false);setSuccess('Ulasan dihapus.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const visible=reviews.filter(r=>filter===0||r.rating===filter);
 return <section id="ulasan" className="reviews-section"><div className="reviews-heading"><div><span className="eyebrow">CERITA DARI PENGGUNA</span><h2>Pengalamanmu berarti.</h2><p className="muted">Bagikan hal yang membantu dan yang masih bisa diperbaiki.</p></div><MessageSquare size={28} aria-hidden="true"/></div>{!supabase&&<p className="review-demo">Demo lokal · Ulasan hanya tersimpan di browser ini dan tidak dipublikasikan.</p>}
 <div className="reviews-layout"><div><div className="rating-summary"><div><strong>{stats.total?stats.average.toLocaleString('id-ID',{maximumFractionDigits:1}):'—'}</strong><span> / 5</span><Stars rating={Math.round(stats.average)}/><small>{unavailable?'Belum tersedia':loading?'Memuat…':stats.total + ' ulasan' + (reviews.length<stats.total?' · 20 terbaru ditampilkan':'')}</small></div><div className="rating-distribution">{[5,4,3,2,1].map(r=><div key={r}><span>{r} <Star size={12} aria-hidden="true"/></span><div className="progress"><i style={{width:stats.total?`${stats.counts[r-1]/stats.total*100}%`:'0%'}}/></div><small>{stats.counts[r-1]}</small></div>)}</div></div><div className="review-filters" aria-label="Filter rating">{[0,5,4,3,2,1].map(r=><button key={r} aria-pressed={filter===r} className={filter===r?'selected':''} onClick={()=>setFilter(r)}>{r?`${r} bintang`:'Semua'}</button>)}</div>{loading?<div className="skeleton review-skeleton" aria-label="Memuat ulasan"/>:visible.length?visible.map(r=><article className="review-item" key={r.id}><div className="review-author"><span className="avatar">{r.display_name.slice(0,1).toUpperCase()}</span><div><strong>{r.display_name}</strong><Stars rating={r.rating}/></div><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}</time></div><p>{r.body}</p>{r.updated_at!==r.created_at&&<small className="muted">Diperbarui {new Date(r.updated_at).toLocaleDateString('id-ID')}</small>}</article>):<div className="review-empty"><MessageSquare size={24} aria-hidden="true"/><strong>{unavailable?'Ulasan belum tersedia.':filter?'Belum ada ulasan dengan rating ini.':'Belum ada ulasan.'}</strong><p>{unavailable?'Coba lagi setelah koneksi tersedia.':'Pengalaman pertama bisa membantu pengguna berikutnya.'}</p></div>}</div>
 <aside className="panel review-form-panel"><h3>{own?'Kelola ulasanmu':'Tulis ulasanmu'}</h3><p className="muted">Satu ulasan per akun. Kamu bisa memperbaruinya kapan saja.</p>{supabase&&!user?<div className="review-login"><p>Masuk untuk membagikan pengalamanmu.</p>{onLogin?<button className="button primary" onClick={onLogin}>Masuk untuk menulis</button>:<a className="button primary" href="/">Masuk melalui beranda</a>}</div>:<form className="form" onSubmit={submit}>{own&&<button className="text-button" type="button" onClick={()=>{setName(own.display_name);setRating(own.rating);setBody(own.body);setConsent(false);setSuccess('');}}><Pencil size={15}/>Edit ulasan sebelumnya</button>}<fieldset><legend>Rating pengalamanmu</legend><div className="rating-picker" role="radiogroup" aria-label="Rating pengalaman"><span className="sr-only">Pilih satu sampai lima bintang</span>{[1,2,3,4,5].map(r=><button role="radio" aria-checked={rating===r} aria-label={`${r} bintang`} type="button" key={r} onClick={()=>setRating(r)}><Star size={26} fill={r<=rating?'currentColor':'none'} className={r<=rating?'filled':''}/></button>)}</div><small className="muted">{rating?`${rating} dari 5 bintang`:'Pilih rating'}</small></fieldset><label>Nama yang ditampilkan<input required minLength={2} maxLength={60} value={name} onChange={e=>setName(e.target.value)} autoComplete="nickname" placeholder="Nama atau nama panggilan"/></label><label>Ulasan<textarea required minLength={10} maxLength={1000} value={body} onChange={e=>setBody(e.target.value)} rows={4} placeholder="Apa yang membantu kamu mengatur keuangan?"/><small>{body.length}/1.000 karakter</small></label><label className="checkbox review-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{supabase?'Saya setuju nama dan ulasan tampil publik.':'Saya paham ulasan demo ini hanya disimpan lokal.'}</label><p className="field-hint">Jangan tulis nomor rekening, email, atau informasi keuangan pribadi.</p><button disabled={busy} className="button primary full">{busy?'Menyimpan…':own?'Perbarui ulasan':'Kirim ulasan'}</button></form>}{own&&<button className="text-button danger" disabled={busy} onClick={remove}>Hapus ulasan saya</button>}{error&&<p role="alert" className="form-error">{error}</p>}{success&&<p role="status" className="review-success"><Check size={16}/>{success}</p>}</aside></div></section>;
}
function Stars({rating}:{rating:number}){return <div className="review-stars" aria-label={`${rating} dari 5 bintang`}>{[1,2,3,4,5].map(r=><Star key={r} size={14} fill={r<=rating?'currentColor':'none'} aria-hidden="true"/>)}</div>;}
