'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Star,MessageSquare} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import type {Review} from '@/lib/reviews';
export default function Reviews({demo=false}:{onLogin?:()=>void;demo?:boolean}){
 const [rows,setRows]=useState<Review[]>([]),[total,setTotal]=useState(0),[average,setAverage]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async(offset=0)=>{setLoading(true);setError('');try{if(!supabase||demo){setRows([]);setTotal(0);setAverage(0);return;}const [r,s]=await Promise.all([supabase.rpc('list_public_reviews_page',{p_offset:offset}),supabase.rpc('review_summary')]);if(r.error||s.error)throw new Error('Ulasan belum tersedia. Coba lagi nanti.');setRows(old=>offset?[...old,...r.data]:r.data||[]);setTotal(Number(s.data?.[0]?.total||0));setAverage(Number(s.data?.[0]?.average||0));}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[demo]);
 useEffect(()=>{void load();},[load]);
 return <section id="ulasan" className="reviews-section"><div className="reviews-heading"><div><span className="eyebrow">PEMBELIAN TERVERIFIKASI</span><h2>Ulasan Pelanggan</h2><p className="muted">Pengalaman pembeli setelah pembayaran disetujui dan ulasan diperiksa admin.</p></div><MessageSquare size={28}/></div><div className="rating-summary"><strong>{total?average.toLocaleString('id-ID',{maximumFractionDigits:1}):'—'}</strong><span>/5 · {total} ulasan</span></div>{rows.map(r=><article className="review-item" key={r.id}><div className="review-author"><strong>{r.display_name}</strong><span className="review-stars" aria-label={`${r.rating} dari 5 bintang`}>{[1,2,3,4,5].map(n=><Star key={n} size={16} fill={n<=r.rating?'currentColor':'none'} aria-hidden="true"/>)}</span><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleDateString('id-ID')}</time></div><p>{r.body}</p></article>)}{loading&&<p role="status">Memuat ulasan…</p>}{error&&<p role="alert" className="form-error">{error} <button className="text-button" onClick={()=>load()}>Coba lagi</button></p>}{!loading&&!error&&!rows.length&&<p className="review-empty">Belum ada ulasan disetujui. Setelah pesanan terverifikasi, bagikan pengalamanmu melalui riwayat pembelian.</p>}{rows.length<total&&!loading&&<button className="button secondary" onClick={()=>load(rows.length)}>Lihat lebih banyak</button>}<p className="muted"><Link href="/?view=premium">Buka riwayat pembelian untuk memberi atau mengedit ulasan.</Link></p>{demo&&<p className="review-demo">Demo · Tidak mengirim atau menampilkan ulasan pengguna.</p>}</section>;
}
